pmgbergen/porepy

src/porepy/numerics/fv/mpsa.py
src/porepy/utils/mcolon.py

Zero out rows in sparse matrix by changing the A.data directly instead of slicing the matrix. Fixes issue #6

Fixed memmory problems in mpsa

---

src/porepy/fracs/structured.py
src/porepy/grids/gmsh/mesh_2_grid.py

We need something similar for 2d domains, and for Cartesian fractures.

Add fracture id to 2d fracture grids.

---

src/porepy/fracs/simplex.py
test/integration/test_split_grid.py

This should do the trick.
Also added geometric tolerances as kwarg in 2d meshing.

Fix meshing in 2d when fractures intersect in L. Resolves #22.

---

src/porepy/fracs/simplex.py

Follow up related to #22 (reopened) - previous attempt to resolve was
not good enough.

Bugfix in meshing of 2d fractures - splitting of intersecting fractures.

---

examples/example1/benchmark1/test_vem.py
examples/example1/benchmark4/vem.py
examples/example4/test_dual_varying_k.py
examples/example4/test_dual_varying_k_surface.py
examples/example4/test_dual_varying_k_surface_1.py
examples/example5/test_upwind_examples.py
examples/example8/test_advection_diffusion_coupling.py
src/porepy/__init__.py
src/porepy/numerics/elliptic.py
src/porepy/numerics/fv/fvutils.py
src/porepy/numerics/fv/source.py
src/porepy/numerics/vem/hybrid.py
src/porepy/numerics/vem/vem_dual.py
src/porepy/numerics/vem/vem_source.py
test/integration/test_darcy.py
test/integration/test_dual_darcy.py
test/integration/test_fvutils.py
test/unit/test_dual_vem.py

- introduce the source for dual formulation problems
- remove the source term from the dual vem
- introduce the dual elliptic class
- introduce some test for the latter

Introduce the dual elliptic class and tests

---

src/porepy/viz/exporter.py

Created a dedicated function to sort point on a face plane in 3d.
Speedup due to skipping of tests etc. Looks to be at least 70% decrease
in time.

Speedup of export of 3d grids.

---

src/porepy/numerics/vem/vem_source.py

very simple update to fix an error for the vem source term in dfn setting

Update the vem source for the dfn case

---

requirements-dev.txt
requirements.txt

Looks like this package is an implicit dependency for some package. The
problem may only appear on Windows.

Added 'six' to requirements. Closes #77

---

src/porepy/fracs/simplex.py

Fix of physical names from gmsh after update of meshio.

---

.travis.yml
test/regression/run_cron_test.sh

Running it for every push is too time consuming.

Test docker only on cron tests.

---

requirements-dev.txt
requirements.txt

To avoid issues related to how meshio handles .msh files, fix the meshio version to something that does not create trouble.

Fix meshio version

---

examples/example3/test_simple_networks.py
src/porepy/fracs/fractures.py
src/porepy/fracs/importer.py

@keileg , the branch fixed the problem and in my opinion is ready to be merged.

Geiger 3d mesh

---

src/porepy/fracs/fractures.py
src/porepy/fracs/importer.py
src/porepy/fracs/simplex.py
src/porepy/numerics/fv/mpsa.py
src/porepy/numerics/mechanics.py
src/porepy/numerics/vem/vem_dual.py
test/unit/test_1d_elimination.py
test/unit/test_graph.py
test/unit/test_structured_grids.py
test/unit/test_tpfa.py

remove the print in all the files in the folders:
- src/porepy/
- test/*
I didn't touch the examples.

remove print in favor of the logger. remove few useless print

---

examples/example1/benchmark4/vem.py

fix for issue #130 
the code works now

update benchmark4 for vem to the new interfaces

---

test/unit/test_vtk.py

not much to say, after the checks I'll do the merge. basically the problem was related to the mortar exporter and some float that now are int.

update the vtk test, now it runs also locally

---

examples/papers/legacy_mortar/example_1.py
examples/papers/legacy_mortar/example_1_data.py
examples/papers/legacy_mortar/example_2_data.py
examples/papers/legacy_mortar/solvers.py
setup.py
src/porepy/__init__.py
src/porepy/fracs/split_grid.py
src/porepy/grids/gmsh/gmsh_interface.py
src/porepy/grids/grid.py
src/porepy/grids/refinement.py
src/porepy/numerics/fem/p1.py
src/porepy/viz/exporter.py
test/unit/test_tag.py
test/unit/test_vtk.py

- re-run the test case for the legacy paper
- update the export vtk to handle in a proper way simplicial grids with P1 solution

Rerun legacy

---

test/unit/test_bc_vectorial.py

unittest for vectorial boundary conditions

---

examples/papers/arXiv_1809_06926/case1/main.py
examples/papers/arXiv_1809_06926/case2/main.py
examples/papers/arXiv_1809_06926/case3/main.py
examples/papers/arXiv_1809_06926/case4/main.py

The import statements have not been updated after the folder was updated
with arXiv name.

Fix import path in runfiles for benchmark 3D dfm.

---

src/porepy/fracs/meshing.py
src/porepy/fracs/simplex.py
src/porepy/fracs/split_grid.py
src/porepy/grids/constants.py
src/porepy/grids/gmsh/gmsh_interface.py
src/porepy/grids/gmsh/mesh_2_grid.py
src/porepy/utils/sort_points.py
test/unit/test_tag_gmsh.py

- the boundary in gmsh are physically tagged
- the boundary, fractures, and auxiliary physical tags are propagated in pp face tags
everything works only in 2d. One test is added. In principle all the physical tags associated to faces from gmsh are kept in pp, so far only the standard one are tested.

Gmsh tags - 2d

---

.travis.yml
examples/papers/flow_upscaling/fracture_sets.py
examples/papers/flow_upscaling/test/test_fracture_sets.py
src/porepy/fracs/fractures_2d.py
src/porepy/grids/mortar_grid.py
src/porepy/grids/partition.py
src/porepy/utils/comp_geom.py
src/porepy/utils/sort_points.py
src/porepy/viz/plot_grid.py
test/unit/test_inside_polygon.py
test/unit/test_polygon_intersection.py
test/unit/test_sort_points.py

Also various other updates to utility functions.

Methodology for polygon polyhedron intersection

---

src/porepy/numerics/fv/biot.py
src/porepy/numerics/fv/fv_elliptic.py
src/porepy/numerics/fv/fvutils.py
src/porepy/numerics/fv/mpfa.py
src/porepy/numerics/fv/mpsa.py
src/porepy/numerics/interface_laws/elliptic_interface_laws.py
src/porepy/numerics/interface_laws/empty_discretization.py
src/porepy/numerics/mixed_dim/assembler.py
src/porepy/params/tensor.py
src/porepy/utils/sort_points.py
test/integration/test_DFN.py
test/integration/test_elliptic_interface_laws.py
test/integration/test_fracture_mesh_generation.py
test/unit/test_assembler.py
test/unit/test_sort_points.py

Neumann Boundary-conditions for Biot.
As a bonus, contact interface laws (contact mechanics for Biot) is also included.

Biot fixes

---

src/porepy/fracs/fractures_2d.py
src/porepy/utils/comp_geom.py
src/porepy/viz/fracture_visualization.py
test/unit/test_fracture_importer.py
test/unit/test_fracture_network_class.py

Various minor changes to FractureNetwork2d class.

Fix fracture network 2d

---

examples/papers/arXiv_1809_06926/solvers.py

new ScalarSource name instead of Integral

update solvers.py of the benchmark

---

src/porepy/viz/exporter.py

The exporter used the time step both to count time (as displayed by paraview) and to extend file names to differ between time steps. The latter required the time step to be an int. We remove this, let the file extension by default run from 0 (but can be overridden), and set the time as displayed by paraview when exporting the vtk.
The setup works on my local setup (no unit tests for vtk are run on travis).

Improved vtk time step exporter

---

examples/papers/dfn_transport/example1/post_process.py
examples/papers/dfn_transport/example1/pot.py
examples/papers/dfn_transport/example2/post_process.py
examples/papers/dfn_transport/example2/pot.py

update post process scripts for the dfn_transport study

---

examples/papers/arXiv_1809_06926/case1/post_process.py
examples/papers/arXiv_1809_06926/case2/post_process.py
examples/papers/arXiv_1809_06926/case3/post_process.py
examples/papers/arXiv_1809_06926/case4/main.py
examples/papers/arXiv_1809_06926/case4/post_process.py

update the post process scripts for the benchmark 3d

---

src/porepy/numerics/mixed_dim/assembler.py
test/unit/test_assembler.py
test/unit/test_darcy_mortar.py

Fix of assembler for active/passive variables on edges.

---

src/porepy/geometry/intersections.py

This type of calls are discontinued from np 1.17

No generators in numpy vstack/hstack calls.

---

src/porepy/fracs/mortars.py

The new grid and old grid were rotated to the 2d-plane. However, the
rotation was only defined up to the sign of the normal vector, as the normal vector was
calculated seperatly for each grids. This resulted in some cases in grids that were matched
"upside down"

Fixed bug in matching of 2d grids.

---

src/porepy/__init__.py
src/porepy/models/contact_mechanics_biot_model.py
src/porepy/models/contact_mechanics_model.py
src/porepy/numerics/contact_mechanics/contact_conditions.py
src/porepy/numerics/fv/biot.py
src/porepy/numerics/interface_laws/contact_mechanics_interface_laws.py
test/common/flow_benchmark_2d_geiger_setup.py
test/integration/test_contact_mechanics_biot.py

Two main changes:
Initial state subtracted for the tangential displacement jumps in the contact discretization
Fixed sign mistake in DivU

Transient contact condition

---

src/porepy/fracs/tools.py
src/porepy/grids/coarsening.py
src/porepy/grids/grid_bucket.py
src/porepy/viz/exporter.py
test/unit/test_assembler.py
test/unit/test_grid_bucket.py

The new implementation, in particular some newly won flexibility, will be used in later work.

Change internal data structures in GridBucket. No longer use networkx

---

src/porepy/grids/grid.py
src/porepy/grids/grid_bucket.py
test/unit/test_grid.py
test/unit/test_grid_bucket.py

A trivial fix, but I'll let you approve @keileg

Fixed bug where geometry values in grid bucket used syntax from networkx

---

src/porepy/fracs/meshing.py
src/porepy/models/.#contact_mechanics_model.py
src/porepy/models/abstract_model.py
src/porepy/models/contact_mechanics_biot_model.py
src/porepy/models/contact_mechanics_model.py
src/porepy/models/thm_model.py
src/porepy/numerics/contact_mechanics/contact_conditions.py
src/porepy/numerics/fv/biot.py
src/porepy/numerics/fv/mpsa.py
src/porepy/numerics/linear_solvers.py
src/porepy/numerics/nonlinear/nonlinear_solvers.py
src/porepy/params/bc.py
test/integration/test_fracture_mesh_generation.py
test/integration/test_thm.py
test/unit/test_grid_extrusion.py

Keep track of error and number of iterations for each time step when solving models.
Add temperature source discretization to thm_model.

Model adjustments

---

Install.md

Add some additional installation instructions on using metis and pymetis, gmsh, and paraview to help new users.

Add details on pymetis, gmsh, and paraview

---

src/porepy/models/contact_mechanics_model.py
src/porepy/numerics/nonlinear/nonlinear_solvers.py
src/porepy/viz/exporter.py
test/common/contact_mechanics_examples.py
test/integration/test_thm.py

Fixed the failing contact mechanics tests and updated arguments of exporter from name, folder to file_name, folder_name.

Contact mechanics tests

---

.travis.yml

This is a fix of an error introduced in 00c439d.

fix: Amend PYTHONPATH in travis config.

---

src/porepy/numerics/fv/fvutils.py

allow also the 0d case in the flux computation, for compatibility

---

src/porepy/fracs/simplex.py
src/porepy/grids/grid.py
src/porepy/grids/partition.py
src/porepy/grids/point_grid.py
src/porepy/numerics/fv/biot.py
src/porepy/numerics/fv/fv_elliptic.py
src/porepy/numerics/fv/fvutils.py
src/porepy/numerics/fv/mpfa.py
src/porepy/numerics/fv/mpsa.py
src/porepy/numerics/fv/tpfa.py
src/porepy/utils/setmembership.py
src/porepy/viz/exporter.py
src/porepy/viz/plot_grid.py
test/integration/test_2d_benchmark_geiger.py
test/integration/test_fvutils.py
test/integration/test_mpfa.py
test/integration/test_mpfa_mpsa_partial_update.py
test/integration/test_mpfa_pressure_trace_reconstruction.py
test/integration/test_thm.py
test/unit/test_bc_vectorial.py
test/unit/test_contact_conditions.py
test/unit/test_darcy_mortar.py
test/unit/test_fracture_intersect_boundary.py
test/unit/test_fvutils.py
test/unit/test_mpfa_gravity.py
test/unit/test_mpfa_robin.py
test/unit/test_segment_intersection_3d.py
test/unit/test_sort_points.py

* The internal logic in the mpfa discretization is reworked, based on logic from mpsa / biot. This significantly simplified the implementation.
* Mpfa can now be constructed gradually (reduced memory need), or partially updated.
* Mpfa and tpfa discretize and assemble vector source terms (for instance gravity).

Mpfa cleanup, and vector sources for finite volume elliptic methods

---

src/porepy/viz/exporter.py

The logical error was wrong condition in the if statement checking if time step is given.

Fixed logical error and typo in Exporter.

---

src/porepy/grids/standard_grids/grid_buckets_2d.py

I added option for single vertical fraction, similar to existing option singel horizontal fraction. Also fixed comment for option two fractures intersecting.

added single vertical fracture to grids/standard_grids/grid_buckets_2d

---

src/porepy/fracs/fractures_2d.py

not much to add, not sure if it's possible to add some test since on travis we don't check vtk as far as I remember

add a function to export to vtk 2d fracture networks

---

src/porepy/models/contact_mechanics_biot_model.py
src/porepy/models/contact_mechanics_model.py
src/porepy/models/thm_model.py

Compute stresses from system state for the sequence of contact mechanics models (M, HM, THM).
Will resolve #408

feat: compute stresses from contact mechanics models

---

src/porepy/numerics/fv/fvutils.py
src/porepy/numerics/fv/mpfa.py

Many small changes (will mainly be important for small problems)
* Avoid matrix multiplications in mappings between local, active and global grids, when the three are identical.
* Various trics with sparse matrices
* Use shortcuts when no Robin conditions are present.

speedup: Computational savings in mpfa and fvutils

---

src/porepy/geometry/intersections.py
test/unit/test_intersections.py

Primarily intended for non-matching mortar grids in 3d.

Functionality to match polygon tessalations of different surfaces

---

src/porepy/fracs/fractures_3d.py

Not sure the implementation is waterproof, but it should go a long way.

fix: Keep track of fractures when imposing external boundary on 3d network

---

src/porepy/numerics/contact_mechanics/contact_conditions.py

@keileg introduced a feature preventing fractures with zero tangential traction from being discretised as gliding. This has prevented convergence of the Newton scheme for me. This PR deactivates the feature. 
In terms of code, only a few lines are changed: 
- The actual check for zero tangential traction is removed.
- Change the order of checking values and computing coefficients for gliding cells to avoid dividing by zero. @haakon-e, could you check my logic here? I.e. that the resulting coefficients are not changed in any of the cases.

Turn off contact mechanics feature 

---

src/porepy/numerics/fem/rt0.py
src/porepy/numerics/vem/mvem.py

Could you review this PR @alessiofumagalli ?

RT0 and MVEM fixes for 0d domains after 33b8a4f

---

src/porepy/viz/plot_grid.py

fix: disregard 0d-grids in plot_gb

---

src/porepy/numerics/contact_mechanics/contact_conditions.py

fix: Derivative of gap function in contact mechanics.

---

src/porepy/numerics/discretization.py
src/porepy/numerics/fv/biot.py
src/porepy/numerics/fv/fvutils.py
src/porepy/numerics/fv/mpfa.py
src/porepy/numerics/fv/mpsa.py
src/porepy/numerics/interface_laws/abstract_interface_law.py
src/porepy/numerics/mixed_dim/assembler.py
src/porepy/numerics/mixed_dim/assembler_filters.py
test/integration/test_mpfa_mpsa_partial_update.py

Allows for significant computational changed when the grid and / or parameters are changed.

Partial update of discretizations for Mpsa, Mpfa and Biot.

---

src/porepy/__init__.py
src/porepy/utils/default_domains.py
test/unit/test_default_domains.py

I got way to tired of writing out the full domain dictionary when only wanting a unit square

Added default domains

---

src/porepy/numerics/mixed_dim/assembler_filters.py

fix: ListFilter with empty list has no-pass behavior

---

src/porepy/models/abstract_model.py
src/porepy/models/contact_mechanics_biot_model.py
src/porepy/models/contact_mechanics_model.py
src/porepy/models/thm_model.py
test/common/contact_mechanics_examples.py
test/integration/test_contact_mechanics.py
test/integration/test_contact_mechanics_biot.py
test/integration/test_dilation.py
test/integration/test_thm.py
test/unit/test_contact_conditions.py

Changes:
* Sorted the methods, the files should be easier to navigate
* Changed names for internal methods, now marked with underscores
* typing
* Deleted some unused methods.
The name change of private methods will break classes that are derived from these base classes.

BREAKING: Cleanup of M/HM/THM-contact mechanics models

---

src/porepy/__init__.py
src/porepy/utils/interpolation_tables.py
test/unit/test_interpolation_tables.py

Intended use is operator-based linearization, Voskov style.

ENH: Function interpolation based on tabularization

---

src/porepy/viz/fracture_visualization.py

Just rotate on 20 colors if more than twelve fractures are given

Add infinite colors to fracture viz

---

src/porepy/ad/forward_mode.py
src/porepy/ad/functions.py

[Feature] Added new functions to AD classes

---

src/porepy/numerics/ad/grid_operators.py
test/integration/test_ad_equations.py

Now, it is possible to use scalar sources while defining AD equations. See, in particular, test_ad_equations.py for simple usage.

Add treatment of scalar sources in the AD framework

---

src/porepy/models/thm_model.py

Darcy fluxes need to be initialized before first Upwind discretization. This PR moves the initialization from _set_temperature_parameters to _initial_condition. This avoids overwriting the computed fluxes for each time the former method is called, which happens at the beginning of every Newton iteration.

MAINT: Move flux initialization in thm_model

---

src/porepy/numerics/ad/functions.py

ad functions will no longer support `Local_Ad_array` type objects. This complements the clean-up of `pp.ad.functions` introduced in PR #539.

DEP: ad functions no longer support Local_Ad_array objects

---

src/porepy/fracs/meshing.py
src/porepy/fracs/structured.py
test/integration/test_fracture_mesh_generation.py

Same as pp.meshing.cart_grid(...) but with a pp.TensorGrid instead

Tensor frac

---

src/porepy/numerics/ad/discretizations.py
src/porepy/numerics/ad/equation_manager.py
src/porepy/numerics/ad/grid_operators.py
src/porepy/numerics/ad/operators.py

This PR attempts to provide more informative messages when errors (typically dimension mismatches) are raised during parsing of Ad equations. The format of the error messages, including which information to provide, should be improved, but for that we need more experience.
Also, the PR contains some minor maintenance of the Ad framework.

Readable error messages from Ad parsing

---

src/porepy/numerics/linear_solvers.py

Depending on how the Model's after_newton_iteration() and
after_newton_convergence() methods are implemented, it may be necessary
to call both (in that order) for the computed solution to be stored in
pp.STATE.
Specifically, the ContactMechanics model need this fix to work as
intended.

BUG: Ensure LinearSolver for Models store solution.

---

src/porepy/viz/exporter.py
tests/unit/test_vtk.py

Fix handles export of variables on edges.
Fix to issue #565

Fix export variables on edges

---

src/porepy/utils/sort_points.py

Fix two typos in sort_points

---

pyproject.toml

This simple PR is dedicated to updating PorePy version in the file`pyproject.toml`
@IvarStefansson and @keileg can be merged without revision.

DOC: update porepy version for uneditable installation

---

src/porepy/numerics/ad/operators.py

Fix an issue in evaluation of Ad Operator trees, when the parsing ends up with dividing a numpy array by an Ad_array (this is not possible, but the fix introduces workarounds for what seemed the most relevant cases).
- [] I have added tests that prove my fix is effective or that my feature works
There may be other closely related cases not covered by the current fix. These are not included in the current PR, but are indicated in the comments of the new implementation. Moreover, the new implementation should raise error messages if such uncovered cases are encountered (previously, such cases were silently …

BUG: Fix uncovered case in division with Ad operators.

---

src/porepy/fracs/split_grid.py
src/porepy/geometry/half_space.py
src/porepy/geometry/intersections.py
src/porepy/grids/grid.py
src/porepy/grids/grid_extrusion.py
src/porepy/models/abstract_model.py
src/porepy/numerics/ad/discretizations.py
src/porepy/numerics/fracture_deformation/contact_conditions.py
src/porepy/numerics/fv/mpsa.py
src/porepy/numerics/linalg/matrix_operations.py
src/porepy/numerics/mixed_dim/assembler.py

This PR contains minor updates that were necessary to make `mypy` happy after `numpy` was updated to v1.22. To changes to functionality in any sense.

STY: Updates related to mypy to comply with numpy v1.22

---

.github/workflows/ci.yml
Readme.md

Numpy v1.22 does not support Python 3.7, and the resulting
incompatibilities have started to show in PorePy, so we will drop
support as well.
Describe the big picture of your changes here to communicate to the maintainers why the pull request is necessary and why we should accept it. If it fixes a previously reported bug, be sure to link to that issue. Please also summarize the changes to the code.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered. Also add any further comments which might be of …

BLD: Drop support for Python 3.7.

---

.github/workflows/push-docker-image.yml

Attempted fix that (hopefully) will trigger an automatic build of Docker, and push to docker hub, upon acceptance of PRs to develop.
I'm not 100% confident this this will work, but the only way I've found to debug this is trial and error (via PRs, unfortunately).
||Yes|No|NA|
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

Update of automatic docker build

---

setup.py
src/porepy/__init__.py

Version bump after release.
||Yes|No|NA|
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered. Also add any further comments which might be of interest to the reviewer or the user community.

REL: Version bump.

---

dockerfiles/base/Dockerfile
dockerfiles/parse_environment.py

Updates to dockerfiles, in on attempt on activating automatic builds upon push to develop.
||Yes|No|NA|
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered. Also add any further comments which might be of interest to the reviewer or the user community.

BLD: Update to docker files.

---

src/porepy/utils/interpolation_tables.py

Implemented cartesian search for points in interpolation grid.
||Yes|No|NA|
In future work, the interpolation and derivative approximation can be unified such that the point search has only to be performed once (contrary to as it is now, once for interpolation and once for each directional/axial derivative)

Interpolation cart search

---

.github/workflows/push-develop-docker-image.yml
.github/workflows/push-docker-image.yml
.github/workflows/push-stable-docker-image.yml
dockerfiles/base/Dockerfile
dockerfiles/base/set-home-permissions.sh
dockerfiles/stable/Dockerfile

This PR introduces several updates to the Docker images. These now provide (hopefully usable) versions of the develop and main branch, with a functioning PorePy install.
The PR also contains improvements towards automatic building of the images upon acceptance of PRs.
||Yes|No|NA|
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

Update to docker images

---

tutorials/Readme.md

Fixed broken URL link in tutorials/Readme.md
||Yes|No|NA|
|I have not duplicated existing functionality |_|_|&check;|

DOC: fixed url in tutorials Readme.md

---

requirements-dev.txt
requirements.txt
setup.py

Describe the big picture of your changes here to communicate to the maintainers why the pull request is necessary and why we should accept it. If it fixes a previously reported bug, be sure to link to that issue. Please also summarize the changes to the code.
||Yes|No|NA|
|The update is covered by the  test suite |_|_|_|
|The documentation is up-to-date |_|_|_|
|I have not duplicated existing functionality |_|_|_|
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered. Also add any …

BLD: Remove repeated `future` entry and add Mac OS-X in setup.py

---

requirements-dev.txt
requirements.txt
src/porepy/numerics/fracture_deformation/propagate_fracture.py

Describe the big picture of your changes here to communicate to the maintainers why the pull request is necessary and why we should accept it. If it fixes a previously reported bug, be sure to link to that issue. Please also summarize the changes to the code.
||Yes|No|NA|
|The update is covered by the test suite |_|_|x|
|The documentation is up-to-date |_|_|x|
|I have not duplicated existing functionality |_|_|x|
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered. Also add any …

STY/BLD: Comply with mypy and freeze max numba version

---

.github/pull_request_template.md

The purpose of this PR is to simplify the file `pull_request_template.md`. @pmgbergen/porepy-maint, most of your feedback has been incorporated.
||Yes|No|NA|
|The documentation is up-to-date |_|_|&check;|
|I have not duplicated existing functionality |_|_|&check;|

DOC: Update pull_request_template.md

---

requirements.txt

Change numba versions from `>= 0.53.0, < 0.56.1` to `>= 0.56.3`. 
Note that we have to require the newest version of numba (at the moment) to avoid breaking changes with setuptools if older versions are installed in the building process.
None of the checklist items are relevant for this PR.

BLD: Update numba version

---

src/porepy/viz/plot_grid.py

BUG: plot_mdg fix

---

.github/CODEOWNERS

BLD: Update code owners

---

.github/workflows/ci.yml

This is an attempt at fixing a (strange) error relating to the installation of scipy in GitHub actions. Also some other updates of the actions configuration.
None is relevant, all relate to github actions.

BLD: Updates to github actions workflow

---

.github/CODEOWNERS

This is a small fix of what is (hopefully) a typo in the CODEOWNERS file
The PR considers only changes to the GH configuration.

BLD: Minor fix in codeowers

---

.github/workflows/rebase_docs_on_develop.yml

This PR provides a GH action that automatically rebases the docs branch on top of any changes in develop. In this way, documentation as  shown in https://pmgbergen.github.io/porepy/html/index.html will always be based on the newest version of the code.
This PR considers only a GH action.

BLD: GH action for rebasing docs on top of develop

---

src/porepy/geometry/bounding_box.py
src/porepy/models/constitutive_laws.py
src/porepy/models/energy_balance.py
src/porepy/models/fluid_mass_balance.py
src/porepy/models/geometry.py
src/porepy/models/momentum_balance.py
src/porepy/models/run_models.py
src/porepy/models/solution_strategy.py
src/porepy/models/units.py
src/porepy/models/verification_setups/manu_flow_comp_frac.py
src/porepy/models/verification_setups/manu_flow_incomp_frac.py
src/porepy/models/verification_setups/manu_poromech_nofrac.py
src/porepy/numerics/ad/discretizations.py
src/porepy/numerics/solvers/andersonacceleration.py
tests/common/flow_benchmark_2d_geiger_setup.py
tests/integration/models/setup_utils.py
tests/integration/models/test_constitutive_laws.py
tests/integration/models/test_energy_balance.py
tests/integration/models/test_poromechanics.py
tests/integration/test_ad_equations.py
tests/integration/test_fv_disc.py

Main changes related to permeability methods, whose signature and return type are unified with other constitutive laws. Other changes include introducing model methods to create second order tensors, adjustment of aperture computation and updates to DifferentiableTPFA.

Permeability_methods

---

src/porepy/numerics/ad/functions.py

While updating `pp.ad.functions` to comply with mypy 1.0.0, I came across what appears to be an indentation error, see the diff in what is line 371-373 in the new version of the file. 
I am almost certain the extra indentation is correct. If this is not the case, let me know, and I will do a partial revert, but keep the changes needed for the mypy-related update.

BUG: Indentation error in Ad maximum function.

---

src/porepy/applications/building_blocks/models_glossary.py
src/porepy/applications/complete_setups/mandel_biot.py
src/porepy/applications/complete_setups/terzaghi_biot.py
src/porepy/models/constitutive_laws.py
src/porepy/models/energy_balance.py
src/porepy/numerics/ad/_ad_utils.py
src/porepy/numerics/ad/equation_system.py
src/porepy/numerics/ad/grid_operators.py
src/porepy/numerics/ad/operators.py
src/porepy/utils/error.py
src/porepy/utils/porepy_types.py

Fixes oversights from #820, e.g. instances of Array not changed to DenseArray. Also some typing and minor documentation fixes.

Fixup_of_820

---

src/porepy/__init__.py
src/porepy/models/constitutive_laws.py
src/porepy/models/energy_balance.py
src/porepy/models/fluid_mass_balance.py
src/porepy/models/mass_and_energy_balance.py
src/porepy/models/poromechanics.py
src/porepy/models/solution_strategy.py
src/porepy/models/thermoporomechanics.py
tests/integration/models/setup_utils.py
tests/integration/models/test_evaluate_constitutive_laws.py
tests/integration/models/test_rediscretization.py
tutorials/diagnostics.ipynb

Facilitates targeted rediscretization. Closes #834. Do we need a specific test for this functionality?

834 targeted rediscretization

---

src/porepy/models/constitutive_laws.py
src/porepy/models/momentum_balance.py
src/porepy/numerics/time_step_control.py
tests/functional/setups/manu_poromech_nofrac.py
tests/unit/test_time_step_control.py

Change sign of the surface term (stress) when assembled in MomentumBalance. Also improve treatment of fluid flux vector sources at interfaces.
Resolves #849.

Stress_sign

---

src/porepy/models/solution_strategy.py
src/porepy/viz/data_saving_model_mixin.py
src/porepy/viz/exporter.py

Update of multiple time step and iterate solutions was not properly included into the source code. Now the methods after_nonlinear_iteration, after_nonlinear_convergence and initial_condition within solution_strategy.py are up to date with the multiple stored solutions functionality.
There is also a few removals of pp.STATE (updated to pp.TIME_STEP_SOLUTIONS) that were found in the docs of a couple files. 

Fix indexed solution update

---

docs/conf.py

Added links to the `networkx` and `sympy` package docs for intersphinx to create functional links in porepy docs.

Add networkx and sympy intersphinx mapping

---

requirements.txt

The vectorized option in shapely install was removed when shapely was upgraded to v2. Therefore, remove the relevant line from the requirements.
This considers PorePy install only.

BLD: Update requirements.txt

---

src/porepy/numerics/ad/forward_mode.py
src/porepy/numerics/ad/operators.py
tests/unit/ad/test_ad_operator_tree.py

This PR solves #606.  Credits to @mariusnevland.

Feat unary minus

---

tutorials/conventions.ipynb

Fixes issue #898 (sign convention in mechanics).

TUT: Include sign convention of momentum balance equation

---

requirements.txt

Preparing PorePy for the next release of scipy will take some time, so we fix the version for now.
None are relevant.

Temporarily fix scipy version to 1.10

---

src/porepy/numerics/mixed_dim/assembler.py

Fix an error uncovered by the static checks.

STY: Fix mypy error in Assembler

---

dockerfiles/base/Dockerfile
dockerfiles/base/_legacy_conda_dockerfile
dockerfiles/dev/Dockerfile
dockerfiles/stable/Dockerfile

This PR replaces the old conda-based docker image with a less complex pip-based installation. 
The main update is to the file defining the base image, but the files defining the development and stable images have been updated accordingly. Note that the image for the stable branch on DockerHub will not be updated until the next release.
No change to the code base.

Switch to pip-based docker images

---

requirements.txt

Adds seaborn to requirements.txt. The package is used in the diagnostics class.
Resolves #941
Side note: This branch and PR are made from within a devcontainer.

BLD: Add seaborn to requirements

---

src/porepy/models/run_models.py

Allows passing a tailored Solver class in params for use in the three functions in run_models.py

FEAT: Facilitate passing tailored solver in params

---

dockerfiles/base/Dockerfile

Fixup after #1026, I forgot to update the Dockerfile.
Not relevant.

BLD: Update Dockerfile

---

dockerfiles/dev/Dockerfile
dockerfiles/stable/Dockerfile
setup.py
src/porepy/__init__.py

REL: Version bump

---

.github/workflows/run-pytest-all.yml
.github/workflows/run-pytest.yml

Hashing `requirements-dev.txt` is not needed, as this file is no longer in use.

Hashing only `requirements.txt`

---

src/porepy/models/constitutive_laws.py
tests/models/test_constitutive_laws.py
tests/numerics/fv/test_tpfa.py

New constitutive law applying the new differentiable tpfa to Fourier's law

Differentiable Fourier flux

---

examples/__init__.py

DOC: Init file for examples module

---

tests/numerics/fracture_deformation/test_fracture_propagation.py

Use pytest.autouse on a few setup methods. Change the name of one class to make it visible to pytest.

Update test of fracture propagation

---

src/porepy/fracs/fracture_network_2d.py
src/porepy/fracs/fracture_network_3d.py
src/porepy/fracs/meshing.py
src/porepy/models/solution_strategy.py

Minor PR reducing logging levels in fracture network classes (and one place in solution strategy).

MAINT: Reduce logger levels

---

dockerfiles/base/Dockerfile

Introduces vim utility to base docker image. It resolves the issue #1153. 

MAINT: Adds vim utility to base docker image

---

src/porepy/numerics/interface_laws/__init__.py
src/porepy/numerics/mixed_dim/README.md

Deleted init files and Readme from two folders that no longer contained any code.

DEL: init and readme in old directories

---

requirements.txt

This is a temporary fix to avoid the issue with numpy 2.0.

BLD: Fixate numpy version to < 2.0.

---

.github/CODEOWNERS

Omar Duran is no longer a code owner

---

tests/numerics/nonlinear/test_line_search.py
tests/numerics/nonlinear/test_nonlinear_solvers.py

Add test that the line search runs through without errors.

Test for line search

---

src/porepy/compositional/utils.py

Closes #1233
Dropping the usage of `numba.guvectorize` and replacing it by a classical parallelized loop.
`guvectorize` seems to have some open issues involving import time. I was not able to find out exactly why, but most stackoverflow posts recommend dropping it and implementing simply `njit` with parallelization instructions.
- Scoping did not help.
- Dropping the signature did not help as well, since it accesses internally the scalar function and numba cannot compile it then without defining a signature.
The standard `njit` with parallel instructions works just as fine, but it is slightly more code and the resulting function is not a universal numpy function anymore.
The import time of porepy should now be almost the same when `NUMBA_CACHE == True` (by default).
@keileg  please check …

MOD: Replacing usage of numba.guvectorize by numba.njit in compositional.utils

---

src/porepy/__init__.py
src/porepy/applications/material_values/fluid_values.py
src/porepy/applications/material_values/solid_values.py
src/porepy/models/constitutive_laws.py
src/porepy/models/momentum_balance.py

Makes sure non-unitary displacement values are tested.
Minor maintenance/doc, including adding model classes to init.

TST: Add non-unitary characteristic displacement

---

.github/workflows/check_tutorials.yml
.github/workflows/run-pytest.yml

BLD: GH action does not run pytest on 3.10. Tutorials are only checked for 3.12.

---

src/porepy/grids/boundary_grid.py
src/porepy/grids/grid.py
src/porepy/grids/mortar_grid.py

Document grid coordinates

---

src/porepy/applications/convergence_analysis.py

Fixes a small documentation error of the `l2_error` function.

DOC: Fix documentation error in `l2_error` function.

---

src/porepy/models/geometry.py
tests/models/test_geometry.py

Adds a test for local_coordinates + some minor improvements

Test-local_coordinates

---

.github/workflows/check_tutorials.yml
.github/workflows/run-pytest-all.yml
.github/workflows/run-pytest.yml

This is an attempt at fixing an issue on GH actions.

BLD: Install dev version of library libffi

---

tutorials/Readme.md

MIN: Listing tracer tutorial in Readme file for tutorials.

---

dockerfiles/base/Dockerfile
dockerfiles/dev/Dockerfile
dockerfiles/stable/Dockerfile

This should have been done when migrating the project requirements from the old setup to pyproject.

BLD: Update base dockerfile to use pyproject.toml

---

src/porepy/applications/convergence_analysis.py

Rename setup/m/model_setup etc. to model

MAINT: Rename setup to model in convergence_analysis.py

---

src/porepy/applications/test_utils/models.py

MAINT: Rename setup to model in models.py

---

src/porepy/examples/flow_benchmark_2d_case_1.py
src/porepy/examples/flow_benchmark_2d_case_3.py
src/porepy/examples/flow_benchmark_2d_case_4.py
src/porepy/examples/flow_benchmark_3d_case_3.py
src/porepy/examples/mandel_biot.py
src/porepy/examples/terzaghi_biot.py
src/porepy/examples/tracer_flow.py

MAINT: Rename boundary_grid to bg in porepy/examples

---

src/porepy/applications/md_grids/mdg_library.py

MAINT: Rename intf_map to interface_map

---

tests/functional/setups/manu_flow_incomp_frac_2d.py
tests/functional/setups/manu_flow_incomp_frac_3d.py
tests/functional/setups/manu_poromech_nofrac_2d.py
tests/functional/setups/manu_poromech_nofrac_3d.py
tests/functional/setups/manu_thermoporomech_nofrac_2d.py
tests/functional/setups/manu_thermoporomech_nofrac_3d.py
tests/functional/test_manu_flow_incomp_frac.py
tests/functional/test_manu_poromech_nofrac.py
tests/functional/test_manu_thermoporomech_nofrac.py
tests/functional/test_terzaghi.py
tests/grids/test_coarsening.py
tests/numerics/ad/test_equation_system.py
tests/numerics/ad/test_operator_functions.py
tests/numerics/ad/test_operators.py
tests/numerics/ad/test_surrogate_operator.py
tests/numerics/nonlinear/test_line_search.py
tests/numerics/test_time_step_control.py
tests/viz/test_diagnostics_mixin.py
tests/viz/test_plot_grid.py

TST: Name unification in tests

---

src/porepy/examples/flow_benchmark_2d_case_1.py
src/porepy/examples/flow_benchmark_2d_case_3.py
src/porepy/examples/flow_benchmark_2d_case_4.py
src/porepy/examples/flow_benchmark_3d_case_3.py
src/porepy/examples/mandel_biot.py

MAINT: Rename "bounds" and "sides" to "domain_sides" in porepy/examples

---

tests/compositional/test_fluid_mixtures.py
tests/functional/setups/linear_tracer.py
tests/functional/setups/manu_flow_comp_2d_frac.py
tests/functional/setups/manu_flow_comp_3d_frac.py
tests/functional/setups/manu_flow_incomp_frac_2d.py
tests/functional/setups/manu_flow_incomp_frac_3d.py
tests/functional/setups/manu_poromech_nofrac_2d.py
tests/functional/setups/manu_poromech_nofrac_3d.py
tests/functional/setups/manu_sneddon_2d.py
tests/functional/setups/manu_thermoporomech_nofrac_2d.py
tests/functional/setups/manu_thermoporomech_nofrac_3d.py
tests/functional/test_linear_tracer.py
tests/functional/test_mandel.py
tests/functional/test_manu_flow_comp_frac.py
tests/functional/test_manu_flow_incomp_frac.py
tests/functional/test_manu_poromech_nofrac.py
tests/functional/test_manu_thermoporomech_nofrac.py
tests/functional/test_sneddon_2d.py
tests/numerics/ad/test_equation_system.py
tests/numerics/ad/test_grid_operators.py
tests/numerics/ad/test_surrogate_operator.py

TST: Name unification in tests part 2

---

tests/models/test_boundary_condition.py
tests/models/test_constitutive_laws.py
tests/models/test_energy_balance.py
tests/models/test_fluid_mass_balance.py
tests/models/test_geometry.py
tests/models/test_momentum_balance.py
tests/models/test_poromechanics.py
tests/models/test_solution_strategy.py
tests/models/test_thermoporomechanics.py

Remainder of the cases (everything but * -> models) is covered in this PR

Name unification of tests for models

---

src/porepy/applications/boundary_conditions/model_boundary_conditions.py
src/porepy/applications/test_utils/models.py
src/porepy/applications/test_utils/well_models.py
src/porepy/models/energy_balance.py
src/porepy/models/momentum_balance.py
src/porepy/models/protocol.py

Final unification for applications and model folder:
- boundary_grid -> bg
- sides (and more) -> domain_sides

Name unification applications models

---

Install.md

Update Install.md after migration to pyproject.toml

---

.github/workflows/check_tutorials.yml
.github/workflows/run-pytest-all.yml
.github/workflows/run-pytest.yml
.github/workflows/run-static-checks.yml

Make sure pip is updated before installing

BLD: Update pip in github actions

---

tests/numerics/ad/test_forward_mode.py

`test_forward_mode` supports `sparray`.

MAINT: `test_forward_mode` supports `sparray`

---

src/porepy/utils/graph.py

DEPR: Marked the Graph class for future deletion

---

src/porepy/models/constitutive_laws.py

Use more descriptive variable names in specific_volume()

---

Readme.md

DOC: Update supported Python versions in Readme

---

src/porepy/viz/exporter.py
tests/viz/test_exporter.py
tests/viz/test_vtk_reference/mdg_data_selection_grid_0.vtu
tests/viz/test_vtk_reference/mdg_data_selection_grid_mortar_0.vtu
tests/viz/test_vtk_reference/mdg_grid_0.vtu
tests/viz/test_vtk_reference/mdg_grid_mortar_0.vtu
tests/viz/test_vtk_reference/restart/grid.pvd
tests/viz/test_vtk_reference/restart/grid_000002.pvd
tests/viz/test_vtk_reference/restart/grid_0_000002.vtu
tests/viz/test_vtk_reference/restart/grid_mortar_0_000002.vtu
tests/viz/test_vtk_reference/single_subdomain_0d.vtu

Exporter supports 0d Grids and MortarGrids.
Especially note the nuances related to number of nodes in 0d. These should be reviewed closely.

Export_0d_data

---

src/porepy/numerics/nonlinear/line_search.py
src/porepy/numerics/time_step_control.py
tests/numerics/nonlinear/test_line_search.py
tutorials/solution_strategies.ipynb

Change to lower-case in "global_line_search" and "local_line_search".

MAINT: Use lower-case keys for line search

---

src/porepy/models/run_models.py
src/porepy/numerics/nonlinear/nonlinear_solvers.py
src/porepy/utils/ui_and_logging.py
tests/numerics/nonlinear/test_nonlinear_solvers.py
tests/numerics/test_time_step_control.py

MAINT: Unify progressbars

---

tests/regression/test_example_params.py

Made a less error-prone treatment of paths to the source files.

BUILD: Fix tests in Docker 
