pmgbergen/porepy

- src/porepy/utils/mcolon.py
- test/unit/test_mcolon.py
Previously:
```python
a = np.array([1, 2])
b = np.array([1, 2])
c = mcolon.mcolon(a, b)
assert c is None
```
Now: 
```python
a = np.array([1, 2])
b = np.array([1, 2])
c = mcolon.mcolon(a, b)
assert c.size==0
```
Any objections?
> mcolon should return empty array instead of None

- src/porepy/numerics/fv/fvutils.py
The previous value assigned eta=0 at random faces, instead of at the
boundary. This resulted in irregular convergence for analytical test
cases (Dirichlet boundaries)
> Bugfix in assignment of eta for mpfa boundary faces.

- src/porepy/viz/exporter.py
I sometimes have variables that only live on some grids (e.g. mechanical displacement only exist in 3D).
I'm not sure if we want to do this change. What do you think?
> if variable not found in grid, skip!

- src/porepy/numerics/mixed_dim/assembler.py
very easy branch, but I notices a speed up of 10 in the assembly procedure. Now most of the time is spent in the actual discretization and not in other stuff. 
Ciao ciao
> make the assembler more fast by avoiding useless empty sparse matrix creation

- requirements-dev.txt
Somehow, pytest 2.6.1 broke the build. For the moment, fix it to 2.6.0
> Freeze version of pytest-cov

- src/porepy/fracs/fractures.py
The network did not save the boundary.
> Bugfix in FractureNetwork3d impose domain boundary.

- requirements-dev.txt
- requirements.txt
attempt to fix Travis by removing the (not essential) pymetis library
> remove pymetis from requirements and requirements_dev

- src/porepy/numerics/fv/mpfa.py
- test/integration/test_mpfaMultiDim.py
The sign of cell contribution to face pressure reconstruction is now compatible with the face contribution. This part might lack proper testing, since the contribution is zero for Cartesian grids.
> Bug fix in mpfa

- Readme.md
- dockerfiles/Dockerfile
Changed library for vtk to conda-forge.
When installing vtk in docker, this seems to be necessary to get all dependent packages (specifically some packaged assumed to be included in ubuntu).
(clinicalgraphics seems to be down)
> updated dockerfile and readme to include vtk from conda-forge

- src/porepy/models/thm_model.py
The thm model called the bc_values and bc_type methods for the scalar variable instead of temperature.
> Fix temperature bc assignment in thm model

- src/porepy/geometry/map_geometry.py
The input array in the old code is changed inplace, with no way to recreate it unless I pass a copy of p to the method.
See e.g. https://stackoverflow.com/a/25463222 
As a side note, the output `sorted_coord` has not been scaled "back" to the original coordinates.
Try e.g.
```
p = np.array([[2.,4.,6.]]).T.dot(np.atleast_2d(np.arange(10)))
print(p)
sorted_coord, rot, active_dimension, sort_ind = pp.map_geometry.project_points_to_line(p)
print(p)
print(sorted_coord)
```
to reproduce. Notice that both `p` and `sorted_coord` are centered around zero.
If this is intended behaviour, I think we should add a warning in the documentation, as this could cause very confusing errors if e.g. `g.nodes` is passed directly to this method.
> fix: do not change input array

- src/porepy/grids/mortar_grid.py
There seems to be lacking some parantheses to make `self.side_grids.keys` `()` be called properly.
This bug seems to have been introduced ~2 years ago (Commit: https://github.com/pmgbergen/porepy/commit/b5cacbc9cd3fa381533c085cb6f720abe00bd2f5), so it is perhaps safe to say that the attribute isn't used anywhere ([suggested by a quick search](https://github.com/pmgbergen/porepy/search?q=sides&unscoped_q=sides)). 
_A perhaps related question:_
In the same commit (https://github.com/pmgbergen/porepy/commit/b5cacbc9cd3fa381533c085cb6f720abe00bd2f5) a tiny class called `SideTag` is introduced, which is referenced to throughout the current documentation (See: [this porepy search](https://github.com/pmgbergen/porepy/search?q=SideTag&unscoped_q=SideTag)), and is also referenced in the …
> fix: attr MortarGrid.sides not set properly

- src/porepy/utils/sort_points.py
A bug in the method `porepy.utils.sort_points.sort_point_plane` is triggered by `pp.plot_grid(g)`. The following code reproduces the bug.
```
n_cells = np.array([2, 2, 2])
physdims = np.array([10, 10, 10])
gb = pp.meshing.cart_grid(
fracs=[],
nx=n_cells,
physdims=physdims,
)
g = gb.grids_of_dimension(3)[0]
pp.plot_grid(g)
```
The function `sort_point_plane` expects the argument `centre` to be a `3x1` numpy array. However, the method `porepy.viz.plot_grid.plot_grid_3d` passes a `1d`-array of length `3`.
The function `sort_point_plane` needs to following modification:
* `_c = np.atleast_2d(centre)`
* `centre = _c if _c.shape[0]>_c.shape[1] else _c.T`
I examined the bug and tested the proposed fix [on my personal github](https://github.com/haakon-e/mastersproject/blob/develop/PorePy%20develop …
> fix: shape of input array

- src/porepy/fracs/fractures_3d.py
- src/porepy/geometry/constrain_geometry.py
- src/porepy/geometry/intersections.py
- src/porepy/grids/grid.py
- src/porepy/grids/mortar_grid.py
- src/porepy/grids/partition.py
- src/porepy/numerics/fv/fvutils.py
- src/porepy/numerics/fv/mpfa.py
- src/porepy/numerics/fv/upwind.py
- src/porepy/utils/half_space.py
- src/porepy/viz/exporter.py
Moved import statements for little used imports from module- to function level throughout the package. This seems to have reduced time for 'import porepy' with almost a factor of 10.
The main culprit was import of numba, but also of sympy, networkx and other packages.
> Reworked import statements to reduce porepy import time

- src/porepy/models/abstract_model.py
- src/porepy/numerics/discretization.py
- src/porepy/numerics/fv/biot.py
- src/porepy/numerics/fv/mass_matrix.py
- src/porepy/numerics/fv/mpfa.py
- src/porepy/numerics/fv/mpsa.py
- src/porepy/numerics/fv/source.py
- src/porepy/numerics/fv/upwind.py
- src/porepy/numerics/interface_laws/abstract_interface_law.py
- src/porepy/numerics/interface_laws/elliptic_discretization.py
- src/porepy/numerics/vem/vem_source.py
- test/unit/test_assembler.py
Use python's abc class to enforce expected function names for discretization classes.
> Introduce formal abstract classes for discretizations

- src/porepy/fracs/fractures_3d.py
- src/porepy/grids/gmsh/gmsh_interface.py
Fix a bug that caused 1d grids to be constructed on the boundary between polygons that were constraints.
> Fix fractures3d constraints

- src/porepy/numerics/interface_laws/elliptic_interface_laws.py
The mortar equations are written on K or K^-1 form, depending on whether
the neighboring equations are finite volumes or of mixed type
> feat: Scaling of RobinInterfaceLaw.

- src/porepy/numerics/interface_laws/elliptic_interface_laws.py
> fix: RobinCoupling scales mortar-mortar contribution from K^-1 to K.

- src/porepy/viz/exporter.py
The Exporter only updates the grid if a new grid is given for a time step:
https://github.com/pmgbergen/porepy/blob/7d6b67b69efdc4dcb484a027064e8fd7bd712a02/src/porepy/viz/exporter.py#L301-L305
We should therefore always update the VTK in the init to handle the cases
where the grid is not updated in the first time step.
> The Exporter init now always compute the initial VTK.

- src/porepy/models/contact_mechanics_biot_model.py
- src/porepy/numerics/mixed_dim/assembler.py
Removes a case when the assembler discretizaiton is built up gradually in terms of gb.nodes, but the edge discretizations are called multiple times (relevant e.g. for BiotContactMechanics).
> Assembler partial discretization

- src/porepy/grids/grid.py
- src/porepy/grids/grid_extrusion.py
- src/porepy/grids/partition.py
- src/porepy/grids/point_grid.py
- src/porepy/numerics/fv/fvutils.py
- src/porepy/numerics/fv/mpfa.py
- src/porepy/numerics/fv/tpfa.py
- src/porepy/numerics/fv/upwind.py
- src/porepy/numerics/vem/dual_elliptic.py
- test/integration/test_fracture_mesh_generation.py
- test/integration/test_split_grid.py
- test/unit/test_grid_extrusion.py
This pull-request set  the number of faces and nodes from the PointGrid to zero as nodes and faces does not make sense in a 0d grid. Previously ,they where just given the identity mapping to the cell-center. However, this does not work when we have a 0d grid with several (disconnected) cells. 
This is a more conceptual choice, so you @keileg  gets to voice your opinion.
@alessiofumagalli : can you check the lines:
https://github.com/pmgbergen/porepy/blob/4b41d1dca984837b833a68705b4598c0c44ad2b2/src/porepy/numerics/vem/dual_elliptic.py#L155-L160
The 0d grids gives a mass matrix of dimension 0x0 which makes sps.linalg.norm crash. Have I made reasonable choice in setting the norm to 1?
> Zero-dimensional grid should not have faces or nodes

- src/porepy/grids/coarsening.py
- test/integration/test_coarsening.py
When the method coarsen() was called with a single grid, and the call forwarded to generate_coarse_grid(), the argument type of subdiv should be changed from Dict[pp.Grid, Dict[pp.Grid, np.ndarray]] to simply Dict[pp.Grid, np.ndarray]. 
Some work on documentation, in particular on module level. Also changed a few function names to indicate they are private.
More documentation, typing etc. I have no idea whether the method I accessed was the one intended as a the front.
> Bugfix in coarsening, wrong type of argument for single grids.

- src/porepy/grids/gmsh/gmsh_interface.py
This PR has two main contributions. Both are fixes to the `run_gmsh` method in `gmsh_interface.py`.
This commit fixes an issue where if an absolute path is passed to `in_file`, the helper method `_dump_gmsh_log` would determine a non-valid path to `debug_file_name`. Consider especially the line
```
debug_file_name = "gmsh_log_" + fn + ".dbg"
```
for the case where `fn` is a full path. Clearly, this will result in an invalid path.
Otherwise, I have also exclusively used the `pathlib.Path` library to perform all operations, and only converted to string where required.
This commit **tries** to fix an issue for how errors are located in the gmsh logger.
In particular, a typical `Info` message that will be included in the log is:
```
Info: Reading …
```
> fix: gmsh interface path error and bug in log handling

- src/porepy/grids/grid_bucket.py
- test/unit/test_grid_bucket.py
This PR primarily contains 1 fix and 1 new feature. Some minor stylistic changes have also been made.
Commit 53ac1ef7 fixes an issue for `add_node_props` and `add_edge_props` where if a string is passed to the methods, it would add each individual character to the data. This due to strings being iterable and the line: `keys=list(keys)`.
Commit 7c27ff44 adds the argument `overwrite` to `add_node_props` and `add_edge_props`. By default, this argument is set to `True`, so existing behaviour remains the same. However, if you set it to `False`, if the any of the keys to be added already exists on any of the grids or edges, we leave its data unchanged.
I have also made some stylistic simplifications to these methods, which improves code readability (especially for edges).
The other commits are …
> fixes and a feature to pp.GridBucket methods

- src/porepy/numerics/fv/fvutils.py
This save time when the discretization method is invoked multiple times.
> speedup: Let numba block inverter cache compiled function

- .travis.yml
- requirements-dev.txt
- requirements.txt
Travis failed when LLVMlite changed the backend llvm to v9 - this broke numba compilation. Change to newer version of numba to free this.
> Do not specify numba version in requirements

- .dependabot/config.yml
Add dependabot to automatically bump dependencies
For first-time activation, see: https://dependabot.com/docs/config-file/
> build: Use dependabot to bump dependencies

- .github/workflows/ci.yml
- poetry.lock
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- src/porepy/__init__.py
- src/porepy/fracs/fracture_importer.py
- src/porepy/grids/gmsh/gmsh_interface.py
- src/porepy/grids/standard_grids/grid_buckets_2d.py
- src/porepy/models/.#contact_mechanics_model.py
- src/porepy/numerics/vem/dual_elliptic.py
- src/porepy/params/bc.py
- src/porepy/viz/exporter.py
This PR has the main goal of running porepy on Windows OS.
In the process, two main contributions have been made.
1. Relax version restrictions for nearly all dependencies.
2. Use [poetry](https://python-poetry.org/) as dependency manager instead of the plain `requirements.txt` file.
I have tested this sofar as running a script that 
- creates and meshes an unstructured fractured grid
- sets up and runs a biot problem with contact mechanics
- ~~exports the solution to vtk.~~ (not verified yet. Current test failed on an unrelated issue)
If you try to install porepy using Windows OS, a number of conflicts occur. The relaxation of versions of certain dependencies have solved most of these issues.
Cython depends on a C compiler. I have installed [Visual Studio …
> build: PorePy for Windows! and transition to modern dependency management

- src/porepy/__init__.py
- src/porepy/fracs/meshing.py
- src/porepy/numerics/fv/fv_elliptic.py
Two contributions:
1. When tagging faces during splitting of meshes, there was a reference to local point indices instead of global once.
2. A specialized EllipticDiscretization class for the case of zero tangential permeability is introduced. This is intended used for imposing full continuity conditions between two meshes of higher dimension (e.g. two fractures in a DFN setting) in cases where one does not want to eliminate the intermediate lower-dimensional domain.
> Bugfix in mesh splitting, new discretization class

- src/porepy/numerics/mixed_dim/assembler.py
- test/integration/test_biot.py
This PR implements additional logic to assembler filters.
In addition, general improvements to variable naming, documentation and typing is done.
Previously, variable and term filters are constructed by passing a list of variables and terms, respectively, which restricts which operators will be discretized. The filters are "strict" in the sense that only terms contained in the respective filters will pass.
This PR extends this functionality such that you can pass a negative filter. That is: "discretize everything except variables/terms in the respective lists". In this proposal, the negative filters are indicated by prefixing each list item by "!" (means 'not'). 
For example:
`variable_filter = ["!temp"]`.
See also the documentation of `Assembler.discretize`, where I added a few examples. …
> Mixed dim assembler filters

- src/porepy/numerics/contact_mechanics/contact_conditions.py
- src/porepy/numerics/fv/biot.py
- src/porepy/params/data.py
- src/porepy/utils/derived_discretizations/implicit_euler.py
- test/integration/test_biot.py
- test/unit/test_implicit_euler.py
- test/unit/test_parameters.py
Useful for parameters which are usually assigned as a scalar/homogeneous value, but may occasionally be heterogeneous, e.g. cellwise.
For now used in ImplicitUpwind, ImplicitUpwindCoupling, DivU and ColoumbContact.
> Cellwise parameters

- src/porepy/grids/match_grids.py
- src/porepy/utils/error.py
There are far too many options for how to normalize errors! Instead of trying to anticipate them, I introduced "normalizations" to the error computation code, so that the user may specify how to normalize. Defaults to old version, i.e. norm of reference solution.
Also caught a bug and generalized to 0d intersections in the grid matching.
> Error normalization

- src/porepy/numerics/contact_mechanics/contact_conditions.py
Solving dilation within the Newton iterations in contact mechanics is done through the dilation equation
`g = g_0 - tan(dilation_angle) * || u_t ||`
The Jacobian of this method is used to predict the update of the dilation in the next newton iteration:
`u_n^{k+1} = g^k + Dg \dot ( u_t^{k+1} - u_t^{k} )`
where `Dg = dg/du_t` is the Jacobian (derivative) of `g` with respect to `u_t`. We get
`Dg = -tan(dilation_angle) * u_t / || u_t ||`
In the case ` u_t = 0`, the Jacobian is extended to the limit as 
`dg/du_t(|| u_t || = 0) = lim_{|| u_t || -> 0 +} dg/du_t = [t, t]^T` (for 2D fractures), where `t = - tan(dilation_angle)`
This PR fixes an issue where `Dg` in the case ` u_t = 0` was only set in one of the two in-fracture tangential directions.
Previously, the code read
```python
d_gap[-1, :] …
```
> fix: set dilation angle all tangential directions

- src/porepy/__init__.py
- src/porepy/grids/structured.py
- src/porepy/models/contact_mechanics_biot_model.py
- src/porepy/models/contact_mechanics_model.py
- src/porepy/models/thm_model.py
- src/porepy/numerics/discretization.py
- src/porepy/numerics/mixed_dim/assembler.py
- src/porepy/numerics/mixed_dim/assembler_filters.py
- src/porepy/numerics/mixed_dim/discretization_filters.py
- test/integration/test_biot.py
- test/unit/test_assembler.py
- test/unit/test_variable_dictionaries.py
- test/unit/test_vtk.py
Assembler operations (discretize, assembly) can be assembled with a new AssembleFilter class. 
This generalizes the previous rudimentary filtering options. Filtering can now be done on grids (standard grids, interfaces, or couplings), variable and term names. 
Two filters are available through pp.assembler_filters: AllPassFilter (will be invoked unless a filter is set), and ListFilter.
The old active_variables keyword in the assembler is made defunct.
Runscripts may need to be updated due to these changes. The contact mechanics models have been updated as part of this PR.
> feat: Filter Assembler operations

- src/porepy/grids/mortar_grid.py
- src/porepy/numerics/contact_mechanics/contact_conditions.py
- src/porepy/numerics/fv/biot.py
- src/porepy/numerics/interface_laws/contact_mechanics_interface_laws.py
- test/integration/test_contact_mechanics.py
- test/integration/test_contact_mechanics_biot.py
- test/integration/test_dilation.py
- test/integration/test_thm.py
- test/unit/test_contact_conditions.py
The sign convention for the jump operators used in contact conditions is changed, so that an open fracture has a positive normal displacement.
> Change sign convention in contact conditions

- src/porepy/viz/fracture_visualization.py
The visualization routines should take an (optional) axes as argument and plot in this. This pull request only implements this for the fracture_visualization.py module. If no axes is given, the legacy behavior is obtained, except, an axes is returned (instead of None).
> Axis for viz

- src/porepy/geometry/constrain_geometry.py
If the line does not cross the polygon shapely returns a line of length 0. This is only on my desktop computer and not my laptop. The difference must be due to version numbers, even if I have tried to get the same versions. Anyway, I don't think the extra check should hurt (This is the correct branch from pull request #459 )
> Handle lines of length 0 that are returned from shapey

- .gitignore
Small PR to include a few file extensions that should be ignored in MacOS. This will make PR's way easier for Mac users.
> Update .gitignore to include MacOS-related files

- .github/workflows/ci.yml
- src/porepy/numerics/fv/mpfa.py
Was there a reason to convert the matrices to dense matrices, @keileg ? For large grids the conversion is unfeasible (e.g. 200 000 cells -> 64 GB memory)
> Fixed memory bug in MPFA: Sparse matrix was converted to dense

- pyproject.toml
I'm not entirely sure what's causing the error. It seems to be related either to `setuptools` or to `poetry`, or maybe both. Thus, this is more or less a brute force fix. I've found it here: https://github.com/python-poetry/poetry/issues/3001
> Fix bug in pip editable install mode

- src/porepy/fracs/meshing.py
- src/porepy/grids/grid_bucket.py
- src/porepy/grids/grid_extrusion.py
- src/porepy/grids/mortar_grid.py
- src/porepy/numerics/fracture_deformation/propagate_fracture.py
- src/porepy/viz/exporter.py
- test/test_utils.py
- test/unit/test_contact_conditions.py
- test/unit/test_grid.py
- test/unit/test_grid_bucket.py
- test/unit/test_grid_refinement.py
- test/unit/test_mortars.py
This leaves a more robust implementation than previously, when we relied on accessing module-level constants outside the module.
Also, added tests to check pickling of `Grid`, `MortarGrid` and `GridBucket`.
> MortarGrid sides are identified by Enum

- src/porepy/fracs/fractures_2d.py
Should there be an option to not export the tags?
I used this to be able to identify which edges in networkx belongs to which fractures in the network
> ENH: Export labels to networkx in FractureNetwork2D

- src/porepy/viz/exporter.py
> BUG: Remove logging decorator from numba compiled function.

- src/porepy/numerics/fracture_deformation/conforming_propagation.py
- src/porepy/numerics/fracture_deformation/propagation_model.py
- test/integration/test_fracture_propagation.py
When the model methods and attributes were renamed, the .Nd attribute of the propagation models were not updated. This PR simply updates to self._Nd in FracturePropagation, ConformingFracturePropagation and the test.
> BUG: self.Nd to self._Nd in propagation models

- src/porepy/fracs/fractures_2d.py
When a fracture tip is almost touching another fracture an auxiliary point is inserted. For DFN's these auxillary points does not have
a purpose as there is no need to refine the mesh in these areas. 
This Pullrequest therefore make the FractureNetwork2D.prepare_for_gmsh( mesh_args, dfn=True) skip the insertion of auxillary points. As far as I understand this should be OK for DFN's, can you confirm @keileg ?
Note for the future: The pp.fracs.tools.determine_mesh_size(...) should probably change name (it does much more than determining the mesh size).
> ENH: DFN's in 2d does not need auxillary points

- src/porepy/numerics/ad/functions.py
- test/unit/test_ad_functions.py
Several new functions are now available within the ad framework:
- tan
- arcsin
- arccos
- arctan
- sinh
- cosh
- arcsinh
- arccosh
- arctanh
- heaviside_smooth
Their corresponding unit tests are also included in the PR. In addition, tests for missing functions were added.
> Addition of new functions into the ad framework

- requirements-dev.txt
- requirements.txt
Temporal workaround to pass vtk unit tests. Due to a new release of meshio (4.4.1), some tests failed during Github Actions, making (unrelated) new PRs to also fail the checks.
This requirement freezes the version to be strictly lower than 4.4.0, where there are no apparent problems.
> Freeze meshio version: >=4.3.5, <4.4.0

- src/porepy/viz/exporter.py
If you have a mix of cell types (e.g., tetrahedrons and cubes) the entries in the faces_loc will have a different sizes.
numpy tires to vstack the list. Instead we hstack the list before calling unique.
> Make it possible to export cells with different number of faces/nodes

- src/porepy/numerics/ad/equation_manager.py
Problem: For a pp.Ad_array a and a numpy array b (wrapped as a pp.ad.Array), a+b and b+a gave different results; specifically b+a was parsed wrongly. This PR is a minor fix to resolve the issue.
> BUG: Parsing of Ad expressions, combine with np arrays.

- src/porepy/__init__.py
- src/porepy/numerics/time_step_control.py
- test/unit/test_time_step_control.py
A new class for determining the new time step based on the number of iterations of the previous time level is proposed. The time-stepping control either relaxes or restricts the time step. In addition, if convergence is not achieved, it offers the possibility to decrease the time step and recompute the solution a given number of times.
> ADD: Class for time-stepping control

- src/porepy/models/contact_mechanics_biot_model.py
- src/porepy/numerics/ad/discretizations.py
- src/porepy/numerics/interface_laws/elliptic_interface_laws.py
- test/integration/test_ad_equations.py
- tutorials/AdFramework.ipynb
The PR removes the k-inv scaling option, which was deemed to cause more confusion than it was worth. 
Now, the Robin condition \lambda = - \kappa * (p_l - p_h) is discretized in the standard FV way by multiplying the pressure contributions by a matrix with diagonal entries -\kappa * mg.cell_volumes.
> DEP: Remove the k_inv_scaling option from RobinCoupling

- src/porepy/numerics/ad/operators.py
Small bug while returning the previous iteration state of a `MergedVariable`.  The returned `Variable` was created with the parameter `grids=self.grids` for `self._is_edge_var = True`, and vice versa. This was causing a critical error while trying to create a `merged_variable.previous_iteration()`.
> BUG: Error while trying to access the previous iteration of a MergedVariable

- src/porepy/numerics/mixed_dim/dof_manager.py
While pythonic, the += version of additive STATE/ITERATE updating has proven to lead to errors (related to initialization of the values without using deep copies). This PR changes to the slightly uglier and less efficient but far safer d[pp.STATE] = d[pp.STATE] + vals.
> Safer distribute_variable method

- tutorials/grid_structure.ipynb
This PR is intended to improve the tutorial "grid_structure.ipynb" 
* It eliminates a remaining recurrence of  'write_vtk'. Since the 'Exporter' object has no such attribute, it was changed to write_vtu;  
* Since there is no 'export_vtk()' in the source, the comment "Again, see export_vtk() for further documentation." was deleted;
* A typo 'exlain' was fixed.
> Remove write vtk

- src/porepy/models/contact_mechanics_biot_model.py
- src/porepy/models/contact_mechanics_model.py
- src/porepy/numerics/ad/_ad_utils.py
- src/porepy/numerics/ad/discretizations.py
- src/porepy/numerics/ad/forward_mode.py
- src/porepy/numerics/ad/grid_operators.py
- src/porepy/numerics/ad/operators.py
- tests/integration/test_contact_mechanics.py
- tests/integration/test_contact_mechanics_biot.py
This PR resolves the issue of the Ad framework dealing with variables, and some other operators, defined on empty lists of grids or interfaces. This also led to several other corrections being needed throughout the Ad framework, mainly of a rather technical sort.
After this PR, the model classes ContactMechanics and ContactMechanicsBiot can be run in Ad modus without modifications (this used not to be the case). Tests are added to verify this.
Also some minor improvements and maintenance along the way.
> Allow empty lists of lower-dimensional grids and interfaces in Ad framework. Resolves #607

- src/porepy/grids/mortar_grid.py
- src/porepy/numerics/ad/grid_operators.py
- src/porepy/numerics/linalg/matrix_operations.py
- tests/unit/test_grid_refinement.py
- tests/unit/test_matrix_operations.py
This PR takes care of two issues that were detected while using the Ad framework to solve single phase flow on the field case in the 3d flow benchmark (though using different grid parameters than in the official benchmark setup):
1. The memory consumption in the Ad representation of mortar projections was unexpectedly heavy on memory (several GB).
2. Construction of the same projections took much longer than expected (34s on a reasonably fast computer, for reference the grid has 52 grids, and the 3d grid ended up with ~450K cells).
The problem turned out to be the storage format used for the matrix representation of the projections: Depending on the direction of the projection, these can have many more columns than rows (or vice versa) and should be assigned CSC storage (or oposite). 
I …
> Use optimized storage format for projection matrices

- src/porepy/models/abstract_model.py
In `create_grid` of `AbstractModel`, `box` is defined as bounding box of a point cloud. The point cloud however contained merely the point (0,1) twice. By transposing the definition of the points, or as here, hardcoding the two corner points (0,0) and (1,1), this is fixed, and the box indeed represents the unit sqaure.
> Fix definition of box in AbstractModel

- src/porepy/models/slightly_compressible_flow_model.py
The if and else were interchanged during type check of params.
> BUG: Inverted logic in check

- src/porepy/numerics/ad/grid_operators.py
The reported dimension should refer to the dimension of the divergence, not of the grid.
Fix an issue where the old version of the code made the `__repr__` method report wrong matrix sizes for the discrete divergence.
> BUG: Minor fix of __repr__ in Ad divergence

- fetch_content.py
Implement the change suggested in #632: point_in_polyhedron file is fetched to the top directory in PorePy. Also, a reminder to check that this directory is in PYTHONPATH is given.
Resolves #632. Could also be a partial fix for #648.
The previous solution, fetching to `src` directory was unsatisfactory, in that this was unlikely to be (and should not be) in PYTHONPATH.
Another option is to place the file somewhere in PYTHONPATH (which we would need to fetch), or let the user choose which directory to use. This is however rather complex and potentially intrusive; in my opinion the suggested approach is better.
> BLD: Minor change to fetch_external_content.py; point_in_polyhedron test

- src/porepy/numerics/ad/forward_mode.py
- tests/unit/test_ad.py
- tests/unit/test_ad_init.py
Fix issues related to taking `Ad_array`s to negative integer powers. 
Raising numpy arrays to negative integer powers is not allowed (no idea why). Fixed this by selective casting to floats when needed.
Also significantly improved test coverage for the relevant functions. As an observation, it took some effort to realize which special cases must be covered etc., indicating that fully dealing with #645 will be a major undertaking just to cover the forward ad part.
> BUG: Ad_array divide and power functions special cases.

- src/porepy/viz/exporter.py
Bug fix, the current version of pp fails the exporting to vtk in presence of polygonal 2d cells with different number of cell to node relation.
Not sure if the exporter is really tested in pp, which is the reason why I didn't put the first X in the checklist
> fix the exporter for the polygon

- src/porepy/geometry/geometry_property_checks.py
- src/porepy/grids/partition.py
- src/porepy/numerics/fv/fvutils.py
- src/porepy/numerics/fv/mpfa.py
- src/porepy/numerics/linalg/matrix_operations.py
This PR contains several improvements that speed up MPFA discretization (will have a positive effect on MPSA as well). There are no changes to code functionality. 
To summarize:
* Inversion of block matrices, at the core of MPXA discretizations, now uses parallelized numba. This leads to significant speedup of discretization.
* In Mpfa, slight reorganizations of the code (mainly, avoiding to compute the same matrix-matrix products over again) lead to further savings. NOTE: Similar changes have already been done in MPSA, but we might want to revisit that code and see if there are more easy pickings.
* In grid partitioning, a bottleneck in preprocessing before calling metis was essentially removed.
* Improved and modernized other parts of the code that gave minor performance enhancements. …
> Speed improvements for MPFA

- src/porepy/grids/grid_extrusion.py
The new version 5 of flake8 gave an error message for the module grid_extrusion. This PR takes care of the issue.
> STY: Make grid_extrusion compatible with flake8 v5

- src/porepy/models/abstract_model.py
- src/porepy/models/contact_mechanics_model.py
The default linear solver in the models is now PyPardiso's sparse solver. 
The methods _initialize_linear_solver and assemble_and_solve were moved from ContactMechanics to AbstractModel (which is more of a base than abstract class).
||Yes|No|NA|
|The update is covered by the  test suite |&check;|_|_|
> Pypardiso default

- setup.py
- src/porepy/models/abstract_model.py
- src/porepy/models/incompressible_flow_model.py
- tests/unit/test_tag.py
* Make IncompressibleFlowModel use AbstractModel's assemble and solve method instead of overwriting. 
* In assemble_and_solve, we use attribute self.linear_solver to identify the linear solver instead of self.params["linear_solver"]. The attribute is set in _initilaize_linear_solver.
||Yes|No|NA|
|The update is covered by the  test suite |&check;|_|_|
|I have not duplicated existing functionality (on the contrary!) |&check;|_|_|
> ENH: Linear solver

- .github/workflows/ci.yml
- dockerfiles/base/Dockerfile
- requirements-dev.txt
- requirements.txt
By separating production and development requirements, this PR avoids duplicate entries in those files. As a result, the workflow "ci.yml" checks requirements.txt and requirements-dev.txt separately.
||Yes|No|NA|
|The update is covered by the test suite |&check;|_|_|
|The documentation is up-to-date |_|_|&check;|
Pip installation is performed as in https://github.com/pmgbergen/porepy/blob/develop/Readme.md
Conda installation can be performed for:
Production: conda install --file requirements.txt 
Development: conda install …
> BLD: separate reqs and reqs-dev

- requirements.txt
The latest dependabot commit leads to a failing build of PorePy on Python 3.10. Therefore the reversion of this commit is suggested. See explanation in #704.
> Revert dependabot commit changing requirements for numba

- src/porepy/viz/exporter.py
While working on an importer (via meshio), I noticed a bug in the exporter. Meshio defines cell types by the number of nodes and not number of faces per cell. The latter has been used in the current exporter (I believe I introduced this error - at some other location of the code in the exporter, still faces are used to distinguish tets, hex's and polyhedra, and in my opinion this is still OK, as this information does not propagate any further). 
Note, that `test_vtk.py` did not notice this inconsistency as meshio actually overwrites cell types, and the only critical case (for 3d polyhedra) is so easy that there has been never any trouble.
Now, a consistent use of cell types is suggested with this PR. 
_Put an `x` in the boxes that …
> BUG: Use meshio's convention to define cell types.

- src/porepy/models/abstract_model.py
- src/porepy/numerics/linear_solvers.py
- src/porepy/numerics/nonlinear/nonlinear_solvers.py
- tests/integration/test_ad_equations.py
- tutorials/simulation_exporting.ipynb
I have split assemble_and_solve_linear_system into assemble_linear_system and linear_solve. The system is stored as a model attribute as `self.linear_system = (A, b)` in the former method. I removed the unused tolerance parameter and suggest to use something like `self.params["linear_solve_tolerance"]` if the need arises.
Solves #715 
||Yes|No|NA|
|The update is covered by the  test suite |&check;|_|_|
> FEAT: Split assemble_and_solve_linear_system

- .github/workflows/ci.yml
Pinning of python 3.10 version to python 3.10.6  in the CI workflow to avoid failing of mypy during build. This a temporary workaround until (an already existing patch) that fixes the issue is included in a new version of mypy. This closes #728.
Python versions 3.8 and 3.9 are agnostic to this issue.
None of the items included in the checklist are relevant in this case.
> BLD: Pin version of python 3.10 to 3.10.6

- src/porepy/numerics/time_step_control.py
- tests/unit/test_time_step_control.py
Improved sanity check for testing compatibility between scheduled and simulated times when constant dt is used. The sanity check is now outsourced to a static method `is_schedule_in_simulated_times()`. A previous unit test was improved and a new unit test was added. This PR solves #736.
> BUG: Compatibility check between scheduled and simulated times

- src/porepy/__init__.py
- src/porepy/models/contact_mechanics_biot_model.py
- src/porepy/models/run_models.py
- src/porepy/models/slightly_compressible_flow_model.py
- src/porepy/models/thm_model.py
- src/porepy/numerics/time_step_control.py
- tests/common/contact_mechanics_examples.py
- tests/integration/test_ad_equations.py
- tests/integration/test_contact_mechanics_biot.py
- tests/integration/test_dilation.py
- tests/integration/test_thm.py
- tests/unit/test_time_step_control.py
This PR proposes a non-breaking integration of the `TimeSteppingControl` class into time-dependent models. The PR preserves all previous functionality of the models, including natural values of initial time, final time, and time step when the `params` dictionary does not contain the key `"time_manager"` with value `tsc: pp.TimeSteppingControl`. 
Note that this PR does not incorporate any time adaptation into the models (thus the name partial). This will be the natural next step. This PR solves #735, where more information about the integration can be found.
Two main changes have been introduced:
1. Models no longer have time attributes. Instead, all time-related variables are centralised in `model.tsc`.
2.  `run_time_dependent_model()` and `_run_iterative_model()` from `run_models.py` now …
> Partial integration of time-stepping control into models

- .github/workflows/ci.yml
- requirements-dev.txt
This fixes a temporary requirement that actions were run on Python > 3.10.7, relating to an issue in mypy.
Resolves #733. 
> BLD: GH action runs on Python 3.10,*, not fixed to 3.10.6

- src/porepy/viz/plot_grid.py
- tests/unit/test_plotting.py
The function `pp.plot_grid` now doesn't work if you pass `mdg` and `vector_value: str`. The internal function `_quiver` expects the array of shape (3 x n), but the state contains 1D arrays. However, this visualization works if you pass not `mdg`, but `grid`, and `vector_value: ndarray`. In this case, the user ensures that he provides the array of shape (3 x n). So we have 2 cases of behaviour:
1. `mdg` and `vector_value: str` - fails due to an error. `mdg` and `vector_value: ndarray` is not allowed according to the docstring.
2. `grid` and `vector_value: ndarray` - works.
All the examples use the second case. I made a minor fix so the first case is not failing, and verified that it doesn't break the second case.
I provided the tests for both cases. Also, I provided a test for the function …
> Fix plotting vector fields

- mypy.ini
- src/porepy/fracs/fracture_importer.py
- src/porepy/fracs/fracture_network_2d.py
- src/porepy/fracs/fracture_network_3d.py
- src/porepy/fracs/gmsh_interface.py
- src/porepy/fracs/meshing.py
- src/porepy/fracs/msh_2_grid.py
- src/porepy/fracs/structured.py
- src/porepy/fracs/wells_3d.py
- src/porepy/grids/md_grid.py
- src/porepy/grids/mortar_grid.py
- src/porepy/grids/partition.py
- src/porepy/grids/point_grid.py
- src/porepy/grids/standard_grids/md_grids_2d.py
- src/porepy/grids/standard_grids/utils.py
- src/porepy/numerics/ad/equation_manager.py
- src/porepy/numerics/ad/operator_functions.py
- src/porepy/numerics/fv/fvutils.py
- src/porepy/numerics/fv/mpsa.py
- src/porepy/numerics/interface_laws/elliptic_interface_laws.py
- src/porepy/numerics/linear_solvers.py
- src/porepy/numerics/mixed_dim/assembler.py
- src/porepy/numerics/vem/dual_elliptic.py
- src/porepy/params/data.py
After an update, mypy (to v0.99) gave error mesasges at function and method parameters that had the default argument `None`, but were not marked as optional (e.g., `def foo(bar: list = None)` instead of `def(foo: Optional[list] = None)`. This PR resolves all such conflicts.
In addition, the tagging system in the interface between the `FractureNetwork` classes and `Gmsh` (the tags themselves are defined as an enum in the module `GmshInterface`) is used in a more principled manner: We now use numerical tags under geometry processing (this is very convenient when the geometry is defined as numpy arrays, for instance, fractures defined as an array of point indices that are connected), while Gmsh interface mainly uses the Enum form, which is closer to Gmsh, easier to read etc. There are some …
> Fix errors related to mypy v0.99

- src/porepy/models/abstract_model.py
This small PR aims at increasing the flexibility of the `domain_boundary_sides()` method by allowing for specification of a tolerance instead of hardcoding a value.  
In addition, documentation and typing has been updated to current standards.
> Allow for tolerance specification in `domain_boundary_sides()`

- src/porepy/models/abstract_model.py
This PR proposes a refactor of `domain_boundary_sides()` without changing its functionality. First, the output type was converted from a regular tuple to a namedtuple. This facilitates accessing the boundary sides as attributes (without having to check/remember its position in the returned tuple). The second change is related to the way the boundary sides are picked. Now, the distance between the face-centers and the box sides are computed such that it matches a given tolerance.
P.D.: A cool feature of named tuples is that they also behave as regular tuples. Another cool feature is that they can be transformed into dictionaries.
_Put an `x` in the boxes that apply or explain briefly why the box is …
> MAINT: Refactor of domain boundary sides

- src/porepy/numerics/ad/functions.py
- src/porepy/numerics/ad/operator_functions.py
- src/porepy/numerics/ad/operators.py
As discussed with @keileg , in order to establish the new workflow with regards to the docs branch, here an update to docstrings and type annotations of some AD classes and functions.
(src code synchronization with docs).
> Maint ad docs

- src/porepy/geometry/constrain_geometry.py
This is a minor update of the function `geometry.constrain_geometry.lines_by_polygon()`, which uses the dependency `shapely` to find the intersection between line segments and non-convex polygons. After a major upgrade to `shapely`, one of the functions we use changed, and this PR updates the code accordingly. 
The new code is compatible with both the old and new version of Shapely, instead of forcing users to update. The consequences of such an update would likely have been minor to none, but it can be hard to tell. The workaround is properly documented locally in the code.
> Update polygon constraint algorithm to work with shapely v2

- tests/unit/test_vtk.py
In the current develop branch failing tests in test_vtk are strangely buried and seem to suceed. By commenting out a single test, the failure however uncovered. Two issues are identified:
- 3 tests fail due to wrong reference test vtk files introduced in #746 
- The recently introduced parametrization of `test_single_subdomains` seems to be the reason why the tests are not run properly.
Currently this PR does not offer a solution. Though githubs tracking of succeeding and failing tests will be used in the development to track the progress. The boxes below will have to be updated in the process of fixing the bugs.
> Failing tests in test_vtk

- src/porepy/models/constitutive_laws.py
- src/porepy/models/energy_balance.py
- src/porepy/models/fluid_mass_balance.py
- src/porepy/models/material_constants.py
- src/porepy/models/solution_strategy.py
- src/porepy/models/units.py
- src/porepy/models/verification_setups/manu_flow_comp_frac.py
- src/porepy/models/verification_setups/manu_flow_incomp_frac.py
- src/porepy/models/verification_setups/manu_poromech_nofrac.py
- src/porepy/viz/data_saving_model_mixin.py
- tests/integration/models/setup_utils.py
- tests/integration/models/test_constitutive_laws.py
- tests/integration/models/test_energy_balance.py
- tests/integration/models/test_mass_balance.py
- tests/integration/models/test_materials_and_units.py
- tests/integration/models/test_momentum_balance.py
- tests/integration/models/test_poromechanics.py
- tests/integration/models/test_thermoporomechanics.py
- tests/integration/models/test_variables.py
1. Introduces testing for scaling. The functionality is still somewhat experimental, but way better covered than previously. The tests are of integration type, checking that simulations results are identical with and without scaling for all provided model classes. 
2. Fixes some bugs caught by the new tests. 
3. We decided to include the normal gradient in the diffusive interface laws, i.e. division through a/2. Consequently, the normal permeability and thermal conductivity now have the same units as their tangential counterparts (m^2 and W/m/s, respectively).
> Scaling_tests

- src/porepy/grids/partition.py
In the update of networkx to v3, the name of the function to create graphs from sparse matrices was changed. This PR updates PorePy to work with the newest version. On local testing, the update also works with older versions of networkx.
> BUG: Update needed for networkx v3

- src/porepy/grids/standard_grids/utils.py
- src/porepy/models/constitutive_laws.py
- tests/functional/test_terzaghi_biot.py
- tests/integration/test_DFN.py
- tests/integration/test_TpfaMonoCoupling.py
- tests/unit/ad/test_forward_ad.py
- tests/unit/test_array_operations.py
- tests/unit/test_md_grid.py
- tests/unit/test_mortars.py
- tests/unit/test_plotting.py
Allow for empty advective interface flux if the subdomain has no neighboring interfaces. This typically corresponds to a single-domain mdg.
> Advective_flux_no_interfaces

- tests/functional/test_mandel_biot.py
- tests/functional/test_manu_flow_comp_frac.py
- tests/functional/test_manu_poromech_nofrac.py
Some of the funcitonal tests ran the simulation on _collection_, not during test run. I fixed the issue using pytest fixture. Note that as far as I understand, the fixture function is only run once, not once for each test.
> Use fixtures to avoid running simulations on collection

- src/porepy/models/constitutive_laws.py
This PR removes two methods from`pp.models.constitutive_laws` that were mistakenly added in PR #815. These are `mechanical_displacement_trace` and `poromechanical_displacement_trace`.
- [] Minor change (e.g., dependency bumps, broken links, etc).
> Remove displacement trace methods from constitutive laws

- src/porepy/fracs/structured.py
- tests/integration/test_fracture_mesh_generation.py
In Cartesian meshing of fractured domains, the fractures are snapped to the underlying mesh. The subsequent identification of intersections did not consider the snapped fractures, leading to intersection points being identified away from the grid lines, which caused errors.
Also modified one of the meshing tests slightly so that it would have picked up the bug.
NB: I did not modify the surrounding code, e.g., wrap comments etc., since I suspect this being taken care of under #780.
> BUG: Cartesian fracture meshing with intersections

- src/porepy/models/constitutive_laws.py
When projecting the trace operator to neighboring interfaces, the trace must first be prolonged to work on the same set of subdomains  as do the mortar projections.
Also added some documentation.
> BUG: displacement jump aperture missed prolongation

- src/porepy/fracs/fracture_network_2d.py
- src/porepy/grids/mdg_generation.py
- tests/integration/test_mdg_generation.py
Fix bug while creating fracture networks in 2d with the flag `domain = none`. The fix consists of imposing a domain outside the bounding box span by the fractures composing the fracture set based on the tolerance used for geometric computations. This PR solves #846.
Unit tests for 2d and 3d were added.
Note that the documentation of the method `impose_external_boundary` is not updated. This will be properly included in the PR that has to do with the unification of fracture network generation.
> 846 inconsistency in fracture network 2d with domain = none

- .github/workflows/push-develop-docker-image.yml
- .github/workflows/push-stable-docker-image.yml
- .github/workflows/run-pytest.yml
- .github/workflows/run-static-checks.yml
This PR introduces the `workflow_dispatch` keyword in the GH workflows. The `workflow_dispatch` unlocks the possibility of running the workflows manually. The changes are fully backward-compatible.
> Allow for possibility to run workflows manually

- src/porepy/numerics/ad/equation_system.py
Tiny bug fix. The default inverter is called on an explicitly dense matrix.
> BUG: Use np not sps for dense inversion

- src/porepy/models/geometry.py
This PR adds the possibility to pass `meshing_arguments: dict[str, float]` as a model parameter. This unlocks the possibility to control the meshing arguments without having to re-define the method `self.meshing_arguments()`.
> FEAT: Pass "meshing_arguments" from the model parameters

- src/porepy/models/constitutive_laws.py
Replace matmul by mul in friction bound operator to allow for non-scalar (homogenous) friction coefficient.
> BUG: Replace @ by *

- tests/integration/test_TpfaMonoCoupling.py
- tests/integration/test_fracture_propagation.py
- tests/integration/test_mpfa_mpsa_partial_update.py
- tests/integration/test_split_grid.py
- tests/test_utils.py
- tests/unit/ad/test_forward_ad_standard_functions.py
- tests/unit/test_assembler.py
- tests/unit/test_bc_vectorial.py
- tests/unit/test_ccw.py
- tests/unit/test_is_point_in_cell.py
- tests/unit/test_merging_non_conforming_grids.py
- tests/unit/test_mesh_size_determination.py
- tests/unit/test_mpsa.py
- tests/unit/test_plotting.py
Fixes failed tests caused by https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
> TST: np.bool and np.float to bool and float

- src/porepy/grids/standard_grids/md_grids_2d.py
- src/porepy/grids/standard_grids/md_grids_3d.py
- src/porepy/grids/standard_grids/utils.py
This PR fixes a bug where `pp.FractureNetwork3d` was used instead of `pp.create_fracture_network()`. This PR solves #880 .
Deprecation warnings were added to the doctoring of the methods belonging to `porepy.grids.standard_grids`.
> 880 outdated pp.FractureNetwork3d

- src/porepy/models/abstract_equations.py
- src/porepy/models/solution_strategy.py
- src/porepy/numerics/ad/operators.py
Store a Scalar representing the time step and reuse for all equations. This is a first step towards simulations with dynamic time stepping.
> Dynamic_ad_timestep

- src/porepy/models/energy_balance.py
This is a slight improvement of the hint of how to set the Dirichlet boundary condition for the convection term in the energy balance equation. Right now, it may cause errors because it doesn't warn that one must divide by viscosity. Dividing by viscosity is required since later these values are multiplied by the Darcy flux. It is lacking viscosity, so in the mass balance equation we [multiply](https://github.com/pmgbergen/porepy/blob/161bfe14245650ed5eda3434ae445d0f914ad4a5/src/porepy/models/fluid_mass_balance.py#L213) it by the mobility (inversed viscosity). Thus, we must do the same here. @keileg is notified about this change.
_Put an `x` in the boxes that apply or explain briefly why the box …
> FIX: Convection bc hint improved

- src/porepy/fracs/meshing.py
- src/porepy/grids/md_grid.py
- src/porepy/models/constitutive_laws.py
Adding `BoundaryGrid`s were added to a later point in the construction of a `MixedDimensionalGrid`. This avoids introducing errors in the projection between the boundary grid and its parent related to the splitting of faces when making room for fracture grids.
Also added a minor fix in the constitutive law for gravitational forces.
> Fix bug when adding boundary grids to a mixed-dimensional grid

- src/porepy/numerics/fem/rt0.py
- src/porepy/numerics/vem/mvem.py
bug fix 0d grid for rt0 (and mvem), the vector projector should be of size (3, 0) since no vector dofs are associated to a 0d grid.
- [ X] Bugfix (non-breaking change which fixes an issue).
- [X ] The documentation is up-to-date.
- [X ] Static typing is included in the update.
- [X ] This PR does not duplicate existing functionality.
> bug fix 0d grid for rt0 and mvem

- src/porepy/fracs/meshing.py
- src/porepy/grids/boundary_grid.py
- src/porepy/grids/md_grid.py
- src/porepy/models/material_constants.py
- src/porepy/numerics/ad/equation_manager.py
- src/porepy/numerics/ad/equation_system.py
- src/porepy/numerics/ad/operators.py
- src/porepy/numerics/mixed_dim/dof_manager.py
- tests/unit/test_equation_system.py
- tests/unit/test_grid.py
- tests/unit/test_md_grid.py
- tests/unit/test_mortars.py
This PR closes #903. It adds several methods to the mdg in order to work with boundary grids in the same manner as we work with subdomains and interfaces. Some things to notice:
It changes the place of creation of the boundary grids. Previously, they were created outside the mdg, in the function `subdomains_to_mdg`. Now they are created inside the class in order to maintain the agreement between the subdomains and their boundary grids. Thus, if the subdomain is registered in the mdg, the corresponding boundary grid is created automatically. The same applies to subdomain removal. The subdomain can be changed in the process of creation, for instance, when two intersecting fractures are divided. To avoid inconsistency, I added the method `compute_geometry` to the boundary grid, which fetches …
> Extend boundary grid functionality

- src/porepy/numerics/ad/equation_system.py
- src/porepy/numerics/ad/operator_functions.py
- src/porepy/numerics/ad/operators.py
- tests/unit/ad/test_ad_operator_tree.py
As we discussed with @keileg, `operator.tree` slightly disturbs debugging the ad, so I moved its attributes to the `operator` itself.
The minor changes I made are an attempt to improve annotations:
* I reformatted the creation of the enum `Operator.Operations` so now static type checkers can see the enum entries. Values left the same.
* The other thing I changed is the type of `operator.children` (previously `operator.tree.children`) from `Sequence[Operator | AdArray]` to just `Sequence[Operator]`. All the methods inside operators.py treat children as if they are only operators and not the AdArrays. Everything works fine, but mypy complains about that. I removed AdArrays from the signature [here](https://github.com/pmgbergen/porepy/blob/03d2bfc848f3c2950e60de2caafbba301c298163/src/porepy/n …
> Feat prune tree

- src/porepy/numerics/fem/rt0.py
In Scipy 1.11, sps.find() will return indices using row-first ordering, also on CSC-matrices.
Due to this change, the opposite_node computation starts to misbehave.
This PR ensures future compatibility with Scipy 1.11 in RT0.
> changed from sps.find to indices

- examples/terzaghi_biot.py
- src/porepy/applications/md_grids/domains.py
- src/porepy/fracs/structured.py
- src/porepy/geometry/domain.py
- src/porepy/models/constitutive_laws.py
- src/porepy/models/run_models.py
- src/porepy/utils/default_domains.py
- tests/integration/test_mdg_generation.py
- tests/unit/geometry/test_domains.py
Provide default coordinates for "xmin" etc. when creating a box-shaped domain. For convenience in the very common case that xmin=ymin(=zmin)=0. A full purging of explicit declarations of "xmin": 0 etc. was not performed. I think this can wait for the test overhaul.
I suggest @jhabriel does initial review.
> Feat default minimum coordinates

- src/porepy/geometry/map_geometry.py
Fix an error (from flake8) related to two type checks in `map_geometry`.
> STY: Fix flake8 error message

- src/porepy/numerics/ad/operators.py
- tests/unit/ad/test_ad_operator_tree.py
This PR attempts to close #936. By this, we raise `ValueError` early if the user attempts to create an ad variable both on the previous time step and the previous iteration. I also raise `NotImplementedError` if the user attempts to create a variable on more than one previous iteration or time step behind, because it is currently not supported: [here](https://github.com/pmgbergen/porepy/blob/c9bbe84f8ae6caa0676da56828ead33c759f4aed/src/porepy/numerics/ad/operators.py#L826) we take only one `original_variable`, which leads again to an unclear error message.
> MAINT: Raising an error in `previous_iteration` and `previous_timestep`

- dockerfiles/base/Dockerfile
This installs the dependency of matplotlib, which is required to use its default interactive backend "tk-agg" to show images when called from .py file. Otherwise, it does not show images.
> BLD: Added python3-tk to dockerfile

- requirements.txt
- src/porepy/grids/mdg_generation.py
The input validation for cell_sizes has been improved. Code now raises a warning when the domain size is smaller than the informed cell size.
> MAINT: improved input validation on cartesian- and tensor-grids

- src/porepy/fracs/wells_3d.py
Need to compute well grid's tags before creating its boundary grid.
> BUG: Order of operations when creating boundary grids for wells

- src/porepy/applications/test_utils/common_xpfa_tests.py
- src/porepy/grids/partition.py
- src/porepy/numerics/fv/biot.py
- src/porepy/numerics/fv/fvutils.py
- src/porepy/numerics/fv/mpfa.py
- src/porepy/numerics/fv/mpsa.py
- tests/numerics/fv/test_biot.py
- tests/numerics/fv/test_mpfa.py
- tests/numerics/fv/test_mpsa.py
This PR removes a bug from the MPxA discretizations that kicked in for problems of a certain size: To limit their memory footprint, the discretization methods split the grid into subproblems and thereby gradually build the discretization matrices. In this process, faces on the boundary between the subproblems were discretized twice. This is fixed in the current PR.
The test suite has been extended to cover gradual discretization for all MPxA discretizations. To facilitate easy testing, the splitting into subproblems can now be done by passing the number of subproblems, in addition to the traditional controlled based on the estimated maximum memory footprint. The memory-based criterion is given priority, as this is the option which is closest to the original motivation behind the …
> Bugfix in finite volume discretizations for (relatively) large problems

- src/porepy/numerics/ad/functions.py
- tests/numerics/ad/test_functions.py
After replacing .evaluate with .value and .value_and_jacobian, a call to the former for a function wrapped as ad.Function requires handling of arguments of non-AdArray type (e.g. numpy array). This was not implemented for all members of the ad.functions module. PR also contains improved typing of said module.
> BUG: Allow .value calls for ad functions

- src/porepy/numerics/fv/biot.py
- src/porepy/numerics/fv/mpfa.py
- src/porepy/numerics/fv/mpsa.py
- src/porepy/numerics/linalg/matrix_operations.py
This PR refactor and introduce a vectorized solution for the function `invert_diagonal_blocks_python` in file `matrix_operations.py`. The function is 2x faster than numba function for a large block diagonal matrix with irregular block sizes.
> Vectorized block diagonal mat inversion

- src/porepy/models/solution_strategy.py
- src/porepy/numerics/ad/equation_system.py
- src/porepy/numerics/ad/operators.py
- tests/models/test_solution_strategy.py
- tests/numerics/ad/test_equation_system.py
1. Deletes redundant `assemble_subsystem` method from `EquationSystem`. Same functionality is now covered by `assemble`.
2. Add `evaluate_jacobian` parameter to `assemble`.
3. Resurrect test_equation_system, which was deleted by mistake.
> Split equation system assemble method

- src/porepy/grids/md_grid.py
A small bug fix in the `__str__` method of the `MixedDimensionalGrid` class where the number of subdomains were printed instead of the number of interfaces.
> BUGFIX: `__str__` method of `MixedDimensionalGrid` class

- src/porepy/grids/structured.py
The newest version of scipy removed the function meshgrid. This PR replaces the deprecated function with a call to numpy.meshgrid instead (the syntax is the same).
> Make meshing compatible with scipy v1.12

- examples/flow_benchmark_3d_case_3.py
- tests/functional/test_benchmark_3d_case_3.py
This PR introduces the setup for case 3, flow benchmark 3d, as a porepy example. Tests for the sanity of benchmark parameters specification (e.g., effective permeabilities and boundary conditions) are included. 
Idea for a proper test: Ideally, we should try to sample the reference value of the plot over line from the benchmark and compare them with the approximate pressure solutions. Might be a nice little side project for the user group.
> Setup for case 3, flow benchmark 3d

- tests/utils/test_permutations.py
Remove two parameters from test_permutations.test_base_length. The deleted values did not contribute meaningfully to test coverage, but significantly prolonged the run time (at least a few seconds per run).
> Limit number of parameters in test of permutations

- src/porepy/fracs/fracture_network_2d.py
- src/porepy/fracs/fracture_network_3d.py
- src/porepy/fracs/structured.py
- src/porepy/grids/mdg_generation.py
- tests/fracs/test_fracture_network_3d.py
This fixes the issue #877. I unified return types for the methods `FractureNetwork3d.impose_external_boundary` and `FractureNetwork2d.impose_external_boundary`, and updated a test for the changed return value in 3D. I also tried to improve some docstrings and warnings. 
Note: I did not try to investigate the performance issue that @keileg mentioned in the issue discussion, but we can discuss it.
> [MAINT] Fixed issue #877

- src/porepy/models/constitutive_laws.py
- src/porepy/numerics/fv/tpfa.py
- tests/models/test_thermoporomechanics.py
- tests/numerics/fv/test_tpfa.py
The previous implementation of differentiable Tpfa contained a bug which gave non-zero transmissibilities on fracture tips and internal boundaries (where the transmissibilities should be zero, but were not). This PR introduces a fix which by filtering sets the transmissibilites to zero at the relevant faces.
A similar fix was also introduced for the potential_trace function, but this is only relevant for the fracture tips.
A new test that covers the fixed code has been added.
Resolves #1104
Resolves #1107 
Resolves #1108
> Bug in Differentiable Tpfa related to fracture tips and internal boundaries

- src/porepy/models/run_models.py
- src/porepy/numerics/time_step_control.py
- tests/numerics/test_time_step_control.py
Fix for issue #0939. By introducing a new method for `TimeManager` to check when a final time is reached, the time manager now behaves as expected. 
> Fix of issue #0939

- tests/numerics/fv/test_tpfa.py
Remove a undesireable warning while running pytest. 
`PytestCollectionWarning`: cannot collect test class 'TestXYZ' because it has a `__init__ `constructor 
From: `tests/numerics/fv/test_tpfa.py`
> MAINT: Classes with init are not meant to be "collectable"

- mypy.ini
- src/porepy/applications/test_utils/vtk.py
- src/porepy/fracs/fracture_network_2d.py
- src/porepy/fracs/fracture_network_3d.py
- src/porepy/fracs/plane_fracture.py
- src/porepy/fracs/split_grid.py
- src/porepy/geometry/half_space.py
- src/porepy/grids/partition.py
- src/porepy/numerics/ad/operators.py
- src/porepy/numerics/solvers/andersonacceleration.py
- src/porepy/utils/setmembership.py
- src/porepy/viz/diagnostics_mixin.py
- src/porepy/viz/exporter.py
Reduce the import time of PorePy by delaying import of dependencies that may not be needed. 
The dependencies can roughly be divided into three groups:
* Those that are almost always used, e.g. `numpy`
* Those that are only used in special cases, e.g., `seaborn`
* Those that, in an average session, may or may not be used.
This PR tries to postpone the import of the second class until the packages are actually needed. Moreover, some imports of the third type of dependencies are also postponed, but the choice of when to do this is necessarily pragmatic rather than principled. In particular, while I would have liked to postpone import of `matplotlib`, this would have required too intrusive changes to the code.
Anecdotally, import time was cut by 20-30% by these changes.
The only change not …
> BLD: Speed up import by delaying import of dependencies

- src/porepy/applications/md_grids/domains.py
Typing should be indicated by a colon, not equality, or else the parameter defaults to a type
> BUG: Bad use of typing in nd_cube_domain

- src/porepy/models/constitutive_laws.py
- src/porepy/models/fluid_mass_balance.py
- tests/models/test_poromechanics.py
This PR introduce contains a slight modification of the Peaceman well model, and more importantly better documentation of that model. Moreover, the units of some constitutive laws were added.
Consider in particular:
1. For the specific volume in Peaceman, should we take the volume integral over the interface or the subdomain? It seems the former has the better chance of being correct for 1d-3d couplings, but I am not sure.
2. Please pay attention to the formatting in the documentation of units. I prefer this style, but if we want changes, it is best to do that now, and define whatever comes out of it as a template. Also, should we always document in SI units, or are derived units (Pa, N etc.) also okay?
_Put an `x` in the boxes that …
> Documentation and minor change in the Peaceman well model

- src/porepy/models/run_models.py
Addresses #939. PR #1100, which originally addressed the issue, created a method for checking whether final time was reached. The method was not called in the case where progress bars were turned on, causing inconsistent number of time steps. This PR addresses that bug by calling the method final_time_reached() also when progress bars are turned on. 
> Fix inconsistent number of time steps

- src/porepy/models/run_models.py
Inconsistency in time step numbers in:
* Iterative models. Now the check-if-final-time is reached is done by calling the method final_time_reached()
* Progress bar: A rounding error caused visualization of the wrong final time step number. This is fixed by using np.round(), which rounds e.g. the time 199.999999 to 200 instead of rounding down to 199, as the int()-functionality did before.
> BUG: Fix num. time steps for iterative models and in progress bar

- src/porepy/grids/grid.py
- src/porepy/grids/simplex.py
- src/porepy/grids/structured.py
- tests/grids/test_coarsening.py
Updates:
1. Disabled two tests related to the coarsening module. The scipy update permuted the output of what is essentially a sparse.find, leading the test to fail a comparison with a known truth. As the coarsening moduleis deprecated, thus fixing the tests was not prioritized. 
2. Enforce integer format of grid topology information. 
> Make code compatible with scipy v1.13

- tests/functional/test_mandel.py
- tests/functional/test_manu_flow_comp_frac.py
- tests/functional/test_manu_poromech_nofrac.py
- tests/functional/test_manu_thermoporomech_nofrac.py
- tests/functional/test_terzaghi.py
Addresses issue #1140. Reduces number of time steps in the functional tests. They are consistently reduced to 2 time steps to reduce computational cost.
At the time of writing: The time to run the functional tests is reduced from about 40s to 25s (in my laptop).
> 1140 number of time steps in functional tests

- src/porepy/numerics/nonlinear/nonlinear_solvers.py
Bug: Missing break of while loop if progress bar are not turned on. Thus, the nonlinear loop continued running.
> BUG: Honor is_diverged when progress bars are off

- src/porepy/composite/__init__.py
- src/porepy/composite/_core.py
- src/porepy/composite/_flash.py
- src/porepy/composite/base.py
- src/porepy/composite/chem_species.py
- src/porepy/composite/composite_mixins.py
- src/porepy/composite/composite_utils.py
- src/porepy/composite/eos_compiler.py
- src/porepy/composite/equilibrium_mixins.py
- src/porepy/composite/flash.py
- src/porepy/composite/flash_c.py
- src/porepy/composite/npipm_c.py
- src/porepy/composite/peng_robinson/__init__.py
- src/porepy/composite/peng_robinson/_eos.py
- src/porepy/composite/peng_robinson/eos_c.py
- src/porepy/composite/peng_robinson/eos_s.py
- src/porepy/composite/peng_robinson/pr_bip.py
- src/porepy/composite/peng_robinson/pr_components.py
- src/porepy/composite/states.py
- src/porepy/composite/utils_c.py
- src/porepy/examples/geothermal_flow_via_correlations/LinearTracerModelConfiguration.py
- src/porepy/examples/geothermal_flow_via_correlations/tracer_flow.py
- src/porepy/examples/soereide_geothermal.py
- src/porepy/models/compositional_flow.py
- src/porepy/models/compositional_flow_with_equilibrium.py
Modifications involving import in pp.composite and numba caching.
Should eliminate the import overhead completely after the first import now.
Fixing some BC computations in CFLE model
> Numba modifications to eliminate import overhead

- src/porepy/numerics/ad/operators.py
Ensures values for a previous_iteration variable are fetched from the stored values even if `state` is passed to Operator._evaluate.
> BUG: Fetch previous iteration values from storage

- tests/grids/test_coarsening.py
The (deprecated) coarsening module has a few tests that are expected to fail. These used to be marked with `@pytest.mark.skip`, but this is confusing, furthermore, the test make the weekly test run (which includes skipped tests) fail. Using xfail instead should resolve this.
> TST: Use xfail instead of skip to mark expected failures

- src/porepy/fracs/fracture.py
- src/porepy/fracs/fracture_importer.py
- src/porepy/fracs/fracture_network_2d.py
- src/porepy/fracs/fracture_network_3d.py
- src/porepy/fracs/utils.py
- tests/fracs/test_fracture_network_2d.py
2d domains with 64 fractures did not work due to the `edges` array being int8. This PR increases to int32 throughout the code (all inside fracs, mostly related to tagging). Thanks to @jwboth for provoking the bug!
> BUG: Increase digits of integer arrays

- src/porepy/models/solution_strategy.py
- src/porepy/numerics/linear_solvers.py
- src/porepy/numerics/nonlinear/nonlinear_solvers.py
- src/porepy/numerics/time_step_control.py
- tests/numerics/test_time_step_control.py
Dynamic time stepping is a feature of `TimeManager` which was not supported by the models #739. This also fixes the bug mentioned in #1152 and fixes the newly found bug which caused to call `after_nonlinear_failure` twice. I'll point on it at the review.
> [MAINT] Integrated dynamic time-stepper into models

- tests/numerics/test_time_step_control.py
Following @IvarStefansson's suggestion [here](https://github.com/pmgbergen/porepy/pull/1188#pullrequestreview-2115306343), I add one more check to the test. It checks that the AD time step scalar actually receives the updated value of the time step.
> TST: Improved TimeManager integration test

- src/porepy/models/momentum_balance.py
- src/porepy/numerics/ad/functions.py
This PR introduces two minor modifications of the ad.functions:
1. Uses first argument in the case of equality of the arguments of the max function. This impact the tangential contact mechanics and the aperture calculation.
2. Assigns unitary jacobian values for l2_norm of an argument with val=0. Thus, derivative information is nonzero and we avoid special cases where a block of the linear system vanishes.
> Limit-cases-of-ad-functions

- requirements.txt
Scipy v 1.14 introduces changes that make the tests fail. This PR freezes scipy to a safe version.
> Freeze scipy < 1.14

- src/porepy/models/material_constants.py
Adds missing docstring parameter units and consistently uses the parsable format.
> DOC: Consistent unit declaration

- src/porepy/grids/match_grids.py
Passing of wrong parameter caused unwanted behaviour due to the last elif in the function being False.
> BUG: Safeguard against wrong "scaling" passed

- src/porepy/models/solution_strategy.py
- src/porepy/numerics/nonlinear/nonlinear_solvers.py
This PR resolves #1196 by allowing passing of a solver statistics class, which can be a tailored version of `SolverStatistics`. Also resolves #1200 by swapping order of operations inside a Newton iteration.
> 1196-adaptivity-of-solutionstatistics

- src/porepy/models/solution_strategy.py
- src/porepy/numerics/time_step_control.py
- tests/numerics/test_time_step_control.py
Fixed a bug of dynamic time stepping when a time step failed right before meeting the schedule. Also improved documentation a bit.
Update: This also addresses the issue with resetting the iterate values after an unsuccessful time step.
> Improvements and fixes for the dynamic time stepper

- src/porepy/numerics/ad/_ad_utils.py
- src/porepy/numerics/ad/grid_operators.py
- src/porepy/numerics/ad/operator_functions.py
- src/porepy/numerics/ad/operators.py
- tests/numerics/ad/test_operators.py
This addresses #1179. Note that I have not implement hashing for the AD functions, since they are not used by the basic models. This however should not break anything, since right now nothing relies on the hashes.
Sidenote: I considered the original idea to name the new method `__key` with double underscore, however, it leads to the issue. Consider the following code: 
```
class Parent:
def __hash__(self) -> int:
return hash(self.__key())
def __key(self):
return 'hi from parent'
class Child(Parent):
def __key(self):
return 'hi from child'
p = Parent()
print(hash(p))
c = Child()
print(hash(c))
```
The hashes of the parent and the child will be the same (not as we want). This is because the method `__hash__` defined only for the parent always calls the parent's `__key` due to [name mangling …
> FEAT: Hashing

- tests/models/test_boundary_condition.py
Addresses issue #1206. Robin conditions are on the form flux + alpha * potential = G. As alpha goes to zero, the Robin conditions approaches Neumann. As alpha goes to infinity, the Robin conditions approaches Dirichlet. This PR includes a test to ensure that the latter happens. The test covers a scalar problem (mass and energy balance) as well as a vector problem (momentum balance). This PR also improves the setup in the approximate-Neumann-conditions-test which was already present. Special thanks to @IvarStefansson for great assistance!
> 1206 test robin approximating dirichlet

- src/porepy/applications/boundary_conditions/model_boundary_conditions.py
- src/porepy/applications/material_values/solid_values.py
- src/porepy/applications/test_utils/models.py
- src/porepy/models/constitutive_laws.py
- src/porepy/models/geometry.py
- src/porepy/models/material_constants.py
- src/porepy/models/momentum_balance.py
- src/porepy/models/poromechanics.py
- src/porepy/models/thermoporomechanics.py
- tests/models/test_constitutive_laws.py
- tests/models/test_momentum_balance.py
- tests/models/test_poromechanics.py
- tests/models/test_solution_strategy.py
- tests/models/test_thermoporomechanics.py
- tutorials/conventions.ipynb
Introduces a elasto-plastic split of the displacement jump, i.e., [u] = [u]^p + [u]^e. The plastic part is the shear and separation ("full opening") we're familiar with. The elastic part is e.g. Barton-Bandis in the normal direction. In the tangential direction, one may use a linear elastic relation introduced as part of this PR . By choosing the default value of -1 for the elastic tangential stiffness, zero tangential deformation is allowed. 
Breaking and notable changes:
1. maximum_fracture_closure renamed to maximum_elastic_fracture_opening
2. elastic_normal_fracture_deformation now returns the positive value maximum_elastic_fracture_opening-closure, instead of the negative value closure.
3. Introduces elastic_displacement_jump and plastic_displacement_jump in new class …
> Elasto_plastic_fracture_deformation

- src/porepy/numerics/time_step_control.py
- src/porepy/viz/data_saving_model_mixin.py
- tests/numerics/test_time_step_control.py
Changes proposed by @pschultzendorff and I. Addresses issue #1199. 
> MAINT: Change misleading names related to restarting simulations

- src/porepy/models/solution_strategy.py
- src/porepy/numerics/linear_solvers.py
- src/porepy/numerics/nonlinear/nonlinear_solvers.py
- tests/models/test_solution_strategy.py
- tests/numerics/nonlinear/test_nonlinear_solvers.py
- tests/numerics/test_time_step_control.py
Changes proposed by @IngridKJ and I. 
Adresses issues #1219 and #1200.
``model.nonlinar_solver_statistics`` already keeps track of the number of nonlinear iterations, residual norms, and nonlinear increment norms. Thus, any explicit passes of these values between ``SolutionStrategy.after_nonlinear_convergence``, ``SolutionStrategy.check_convergence``, and ``NewtonSolver.solve`` are removed. Conveniently, this fixes ``iteration_counter`` lagging behind by one step. ``NewtonSolver.solve`` only returns one boolean value ``converged`` now.
On an additional note, we noticed that the test suite does not cover the case of divergence due to nan values in ``SolutionStrategy.check_convergence``, i.e., lines 547-551 in ``solution_strategy.py``. We only noticed a mistake in our changes due to flake …
> Remove iteration counter and norms that are already covered by SolverStatistics

- src/porepy/grids/grid.py
- src/porepy/numerics/fv/upwind.py
- tests/grids/test_grid.py
- tutorials/grid_topology.ipynb
Changes:
1. Replaced the (8 year old!) implementation of `cell_face_as_dense` in the `Grid` class. The new implementation is much more transparent, and documented.
2. Renamed the method `cell_face_as_dense` -> `cell_faces_as_dense`.
3. Improved the test for this method.
@IvarStefansson @IngridKJ: Although the test suite is much improved, the old implementation did not fail on this expanded set. I am not sure which grid you used to make the method fail today, but could you test the new version and see if it works? If so, I am not sure if we should expand the test suite with the previously failing grid, so let me know what you think. If it still fails, we will definitely add it.
_Put an `x` in the …
> Reimplemented method cell_face_as_dense in the grid class

- src/porepy/grids/refinement.py
- tests/grids/test_refinement.py
The function `pp.refinement.refine_grid_1d` returned grids with non-sensical topology (the cell-face map was clearly wrong), however this was not covered by the tests.
This PR fixes that issue, and also improves the implementation of the function so that it can be used for grids with non-trivial topology (ordering of cells, faces and nodes which are not linear). The new implementation is also much better documented.
The tests have also been improved. I decided to only test grids that are aligned with the x-axis. This is seemingly a poorer coverage than what used to be the case, however, I found the old tests' focus on geometry misguided; the chances of getting the geometry wrong are miniscule, while the topology is more complex.
Resolves #1277 
What types of changes does this PR introduce …
> Fix function to refine 1d grids. Improve tests.

- tests/functional/setups/manu_flow_comp_2d_frac.py
- tests/functional/setups/manu_flow_comp_3d_frac.py
- tests/functional/test_manu_flow_comp_frac.py
- tests/functional/test_manu_flow_incomp_frac.py
- tests/functional/test_manu_poromech_nofrac.py
- tests/functional/test_manu_thermoporomech_nofrac.py
This PR introduces some documentation updates in functional tests. In addition, some relative errors were corrected (from 50% tolerance to the desired 5% relative tolerance).
These only affected skipped tests. All tests passed locally in my machine.
> Documentation and test fixes in functional tests

- requirements.txt
There is an issue with the tutorial on solver diagnostics that seems related to a recent upgrade to Matplotlib v 3.10. Enforce older versions of matplotlib until we figure out what to do there.
> BLD: Limit matplotlib to < 3.10

- src/porepy/compositional/_core.py
Fixes failing mypy test.
"Members defined within an enum class should not include explicit type annotations.", as per https://typing.readthedocs.io/en/latest/spec/enums.html#defining-members.
> STY: Remove type annotation for Enum members

- src/porepy/fracs/fracture_network_3d.py
- src/porepy/geometry/constrain_geometry.py
- src/porepy/geometry/intersections.py
- src/porepy/grids/simplex.py
- src/porepy/numerics/linalg/matrix_operations.py
Small fixes to take care of deprecation warnings thrown in the following cases:
- The use of scipy.spatial.qhull:
> DeprecationWarning: Please import `Delaunay` from the `scipy.spatial` namespace; the `scipy.spatial.qhull` namespace is deprecated and will be removed in SciPy 2.0.0.
- The use of shapely_speedup.enable():
> DeprecationWarning: This function has no longer any effect, and will be removed in a future release. Starting with Shapely 2.0, equivalent speedups are always available
- Using a single-element array as an int:
> DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
What types of changes does this PR …
> Deprecation warnings

- src/porepy/examples/mandel_biot.py
Addresses issue #1137. The issue reports a possible functional error in mandels_problem.py. The only problem @IvarStefansson and I found while trying to reproduce the issue was some division by zero while plotting (if Cartesian grids were used). A user warning is now implemented and the problematic plotting is skipped in the case of Mandel's problem being run with a Cartesian grid. Please refer to the issue for more detailed breakdown of the problem. 
> Issue with Cartesian grid and MandelSetup

- tests/models/test_geometry.py
Based on issue #1303, we optimized the test to go from 13s to 6s, using `@fixture` for geometry. In this way we only constructed the object once instead of for every test.
> Optimizing test exectution for test geometry

- tests/numerics/ad/test_equation_system.py
Slight update of module-level documentation in `test_equation_system.py`. Closes #1167.
> TST: Minor documentation change in test of EquationSystem

- .github/workflows/check_tutorials.yml
- .github/workflows/run-pytest-all.yml
- .github/workflows/run-pytest.yml
- .github/workflows/run-static-checks.yml
- dockerfiles/base/Dockerfile
For now (and likely until the end of April), we will support Python 3.11-3.13.
Changes included:
1. All GH actions run on 3.13.
2. The base docker image is based on Python 3.13
This PR should not be merged until:
1. The GH action running all tests run successfully. EDIT: OK
2. The Docker build on Python 3.13 has been verified to work. EDIT: OK
> Upgrade to Python 3.13

- src/porepy/applications/profiling/run_profiling.py
The `argparse` argument `--keep_output` in the profiler was initiated with `action="store_true"` and `default=True`. This meant it couldn't be set to `False`. I changed the argument to `--clear_output` with `action="store_true"`, which is automatically initiated with `default=False`. Everything stays the same, except one can now actually use the flag.
> BUG: Fix keep-output command line argument in profiling script

- src/porepy/applications/convergence_analysis.py
- src/porepy/examples/mandel_biot.py
- src/porepy/examples/terzaghi_biot.py
- tests/applications/test_convergence_analysis.py
- tests/functional/setups/manu_flow_comp_2d_frac.py
- tests/functional/setups/manu_flow_incomp_frac_2d.py
- tests/functional/setups/manu_poromech_nofrac_2d.py
- tests/functional/setups/manu_thermoporomech_nofrac_2d.py
I think the title explains it all.
Relevant changes are in `porepy/applications/convergence_analysis` and `tests/applications/test_convergence_analysis`.
Other changes are due to change in name `l2_error -> lp_error`.
> MOD: Replacing l2_error with general lp_error in ConvergenceAnalysis.

- src/porepy/numerics/ad/equation_system.py
- tests/numerics/ad/test_equation_system.py
The new method updates the attributes set during create_variable, removing everything related to the variables to be removed.
> FEAT: Add remove_variables method to EquationSystem

- src/porepy/models/constitutive_laws.py
In the conversion of permeability from a tensor to an Ad operator, the permeability was calculated twice, with the first take effectively tossed away. This PR ensures permeability is only calculated once.
The speedup gained from this is surprisingly large, or negatively, the cost of the conversion to an operator is surprisingly high (though perhaps not surprisingly so). I hope to fix most of this in connection with #1182, but that project requires some more effort to complete.
_Put an `x` in the boxes that …
> SPEED: Avoid double costly evaluation of permeability in constitutive law

- src/porepy/examples/flow_benchmark_2d_case_4.py
Minor updates to the geometry specification.
Observation: There is no test for this benchmark case. I can add one, but would benefit from a short discussion on how to approach the test.
> ENH: Improvements of model geometry settings for the 2d benchmark case 4

- src/porepy/params/bc.py
- src/porepy/viz/exporter.py
When juggling with different numpy versions, I ran into some issues where calls of the type `array.reshape((n_row, n_dim), "F")` were not permitted. This PR changes these few cases to  `array.reshape((n_row, n_dim), order="F")`.
I did a search through the code base, and found no other cases where we used `reshape` with an order argument but without specifying the `order` keyword.
> MAINT: Added keyword to numpy reshape calls

- src/porepy/numerics/time_step_control.py
- tests/numerics/test_time_step_control.py
This is a small change that improves (at least my) experience of using PorePy. When using dynamic time stepping, the lower limit of a time step is by default inferred to be `Δt_min = 0.001 * t_max`. This will raise a mistake if I set the initial time step to be smaller, which is usually desired. Therefore, I must always pass an additional argument to change this limit.
My suggestion is to change this rule for the lower limit to the following: `Δt_min = min(0.001 * t_max, Δt_init)`, because if the user passes a small time step, it is obviously considered within the limits. I don't think this change can harm anything, please let me know if I'm wrong!
Upd: I also updated the corresponding tests to the new behavior.
_Put an `x` in the …
> Minor change: Improved time manager

- src/porepy/fracs/meshing.py
- src/porepy/fracs/split_grid.py
- src/porepy/fracs/tools.py
- src/porepy/grids/coarsening.py
- src/porepy/grids/grid.py
- src/porepy/grids/md_grid.py
- src/porepy/numerics/ad/_ad_parser.py
- src/porepy/numerics/ad/_ad_utils.py
- src/porepy/numerics/ad/equation_system.py
- src/porepy/numerics/ad/grid_operators.py
- src/porepy/numerics/ad/operators.py
- src/porepy/numerics/ad/surrogate_operator.py
- src/porepy/numerics/fracture_deformation/conforming_propagation.py
- src/porepy/numerics/fv/mpsa.py
- src/porepy/numerics/fv/tpfa.py
- tests/numerics/ad/test_equation_system.py
- tests/numerics/ad/test_operators.py
Name unification of the remainder of the source. All cases `(equation_system,` `subdomains` etc.) treated in one go.
I am not sure about the fracs subpackage, in particular the module `split_grid`: Both variable names and documentation (over)use a logic of high and low dimensions, denoted with names like `gh/gl`, `g_h(igh), g_l(ow)`, `sd_primary` etc. etc. I tried to unify the terminology, but I am not confident things have been improved, and there is a risk I added a new layer of confusion. What is really needed is a full refactoring, but that will take hours to days. Please consider if it is better to revert the changes in each of the files in this module (they are separate commits, so reversion is easy).
_Put an `x` in the boxes …
> Unify names most of src

- src/porepy/models/constitutive_laws.py
issue: #1338
Rename sds to subdomains in constitutive_laws.py.
> REF: Rename sds to subdomains

- src/porepy/models/constitutive_laws.py
- src/porepy/numerics/ad/_ad_parser.py
- src/porepy/numerics/ad/forward_mode.py
- src/porepy/numerics/ad/functions.py
- src/porepy/numerics/ad/operators.py
- src/porepy/numerics/linalg/matrix_operations.py
- tests/numerics/ad/test_operators.py
This covers #1319. Made by @IngridKJ and me.
> Sparse arrays

- src/porepy/fracs/fracture_network_3d.py
- src/porepy/fracs/msh_2_grid.py
- src/porepy/fracs/plane_fracture.py
- src/porepy/fracs/split_grid.py
- src/porepy/fracs/structured.py
- src/porepy/geometry/constrain_geometry.py
- src/porepy/geometry/geometry_property_checks.py
- src/porepy/geometry/intersections.py
- src/porepy/models/geometry.py
- src/porepy/numerics/ad/_ad_utils.py
- tests/numerics/vem/test_dual_vem.py
- tests/utils/test_interpolation_tables.py
Mainly plain deletions, but I also expanded documentation at a few points.
Most of the deleted comments were fair and should have been fixed in a world with infinite resources, but chances are they would have gone unaddressed for a few more years if left alone.
- [] Other:
> MAINT: Deleted outdated todos

- src/porepy/examples/mandel_biot.py
- src/porepy/examples/tracer_flow.py
- src/porepy/models/compositional_flow.py
- src/porepy/models/constitutive_laws.py
- src/porepy/models/contact_mechanics.py
- src/porepy/models/fluid_mass_balance.py
- src/porepy/models/geometry.py
- src/porepy/models/protocol.py
- src/porepy/models/solution_strategy.py
- src/porepy/numerics/ad/operators.py
- tests/functional/setups/manu_flow_comp_2d_frac.py
- tests/functional/setups/manu_flow_incomp_frac_2d.py
- tests/functional/setups/manu_poromech_nofrac_2d.py
- tests/functional/setups/manu_sneddon_2d.py
- tests/functional/setups/manu_thermoporomech_nofrac_2d.py
- tests/models/test_geometry.py
- tests/numerics/ad/test_operators.py
As discussed in #1345, the cost of constructing operators for constitutive laws is high, in particular for laws that are called multiple times. This PR introduces a simple caching-mechanism that stores the constructed operator.
Caching is invoked by adding a decorator `@pp.ad.cached_method` on target methods. Though in principle caching can be applied widely, this PR introduces it only in a few selected methods. Profiling indicates that this PR, together with an upcoming PR that targets parameter updates within Newton iterations, removes most if not all the non-standard bottlenecks (those that are not assembly linear solve, rediscretization, exporting) within Newton.
---------------------
UPDATE: Preserving type information for the decorated methods turned out to be non-trivial (for …
> Caching of the construction of constitutive laws in the model framework

- src/porepy/examples/fracture_damage.py
- tests/models/test_fracture_damage.py
This adds an integration test for momentum balance + fracture damage. It also fixes a bug which caused failure of one of the slow tests.
> Extend-damage-testing

- src/porepy/grids/simplex.py
This fixes an issue that likely arose when a call to a PorePy function was changed to `numpy` unique in PR #1386. 
NOTE: The issue is picked up when I run `test_mdg_library` with `--run-skipped` locally (generation of the 3rd 3d benchmark geometry fails) on `numpy v2.0`, but *not* `v2.1.3`, as was done on the latest GH run of all tests. There is thus a workaround that avoids this update, but I don't see any harm in the minor changes suggested.
_Put an `x` in the boxes …
> BUG: Tetrahedral generation from Gmsh, 2d array should be 1d

- src/porepy/models/energy_balance.py
- src/porepy/models/fluid_mass_balance.py
- src/porepy/models/solution_strategy.py
Streamline the evaluation of Darcy flux by 
- Computing fluxes once during before_nonlinear_iteration, storing for all keywords.
-processing all wells, improving performance in the case of many wells.
Please have a look at the placement of affected methods and naming of the new one.
> Optimize Darcy flux evaluation

- src/porepy/grids/coarsening.py
- src/porepy/grids/grid.py
- src/porepy/grids/md_grid.py
- src/porepy/grids/mdg_generation.py
- src/porepy/grids/partition.py
- src/porepy/grids/refinement.py
- src/porepy/grids/simplex.py
After discussion with @keileg, the following unused functions have been marked as deprecated.
1. ../src/porepy/grids/grid.py
- get_internal_nodes()
- get_boundary_nodes() (only referenced by get_internal_nodes())
- get_internal_faces()
2. ../src/porepy/grids/partition.py
- partition_grid()
3. ../src/porepy/grids/simplex.py
- TriangleGrid.cell_node_matrix()
> Deprecate unused code in the grid library

- .github/workflows/run-static-checks.yml
- src/porepy/applications/test_utils/grids.py
- src/porepy/applications/test_utils/vtk.py
- src/porepy/models/compositional_flow.py
- src/porepy/numerics/fv/biot.py
- src/porepy/numerics/fv/mpfa.py
- src/porepy/numerics/fv/mpsa.py
- src/porepy/numerics/fv/tpfa.py
- src/porepy/numerics/fv/tpsa.py
- src/porepy/utils/graph.py
- src/porepy/viz/exporter.py
- tests/compositional/test_materials.py
- tests/params/test_tensor.py
- tests/utils/test_array_operations.py
- tests/viz/test_exporter.py
Notable changes:
1. I had to make a minor adjustment to the GH action for static tests to allow for a mypy update. The new version of the file seems reasonable. For explanation, see documentation in the action setup.
2. Mypy found a bug related to update of Biot discretizations. In my understanding, this also indicates that test coverage of this part is not good enough (as expected). I added a warning statement related to the update option in mpfa, mpsa, and biot. Though we have not prioritized to fix this yet, it may become a more pressing issue in the future.
Besides this, the changes are rather small.
There is one remaining mypy issue for which I may need your assistance, @vlipovac: The `_MixtureDofHandler` defines a read-only property `overall_fraction_variables`, which is also …
> Updates related to mypy v 1.16

- src/porepy/viz/plot_grid.py
This makes `plot_grid` raise an error if an incorrect argument was passed. Previously, it returned successfully and did nothing, which was confusing (at least for me).
> Maint: Error handling in `plot_grid`

- src/porepy/models/solution_strategy.py
Slightly improve performance by avoiding to create default TimeManager if one is passed in Model parameters.
> MAINT: Avoid creating default TimeManager if one is passed to Model

- tests/functional/test_sneddon_2d.py
…pdates
The old setting turned out to give an error when Gmsh was updated to version 4.14. Updated both the reference value for order of convergence and increased the tolerance, in the hope that we will be less sensitive to Gmsh updates in the future.
Resolves #1463.
> TST: Sneddon test is less restrictive to reduce sensitivity to Gmsh updates

- src/porepy/numerics/ad/equation_system.py
… data fetching
This PR contains a targeted optimization to the EquationSystem.get_variable_values() method, which can significantly reduce simulation time in cases with many variables and shared subdomains. Motivated by compositional simulations.
The updated method avoids redundant operations by:
- Using a set for faster lookup of variable IDs.
- Caching domain data to prevent repeated self._get_data() calls.
- Returning an empty vector via np.empty(0) instead of np.array([]).
These changes reduce unnecessary memory operations and domain-level lookups, which previously contributed substantial overhead during per-iteration routines such as thermodynamic property updates and auxiliary computations / evaluate() method.
Benchmarking: On a water–salt multiphase system with ~3222 mdg cells, …
> Optimize get_variable_values method of EquationSystem class

- src/porepy/models/run_models.py
- src/porepy/numerics/nonlinear/nonlinear_solvers.py
- src/porepy/utils/ui_and_logging.py
`tqdm` with another weird bug again. In `ui_and_logging.py`, `progressbar_class` was either `trange` or `DummyProgressbarClass`. At some point, `_TqdmLoggingHandler.emit` calls `progressbar_class.write`. This raises an error, as `trange` is not actually a class, but a function that returns an instance of the `tqdm.tqdm` class. 
I fixed this s.t. `progressbar_class` is now either `tqdm` or `DummyProgressbarClass`, which comes at the miniscule cost that the progressbars have to be initialized with a range instead of an int.
Not sure how this slipped through tbh. When I tested things for #1450, this error never appeared for some reason that I do not understand.
Thanks for catching the bug @jwboth !
> BUG: Replace trange with tqdm to avoid a logging bug

- src/porepy/numerics/fv/upwind.py
This PR exposes the flux array key for both Upwind and UpwindCoupling. This enables reusing the Upwind class for advecting directions different from a Darcy flux.
> Expose configurable flux array key in Upwind and UpwindCoupling

- src/porepy/grids/grid.py
- tests/grids/test_grid.py
This fixes an error introduced in #1475: When calculating cell diameters it is necessary, first to take the maximum of all diameters (node-node distances) within a cell, and then apply a user-defined function (say, `np.min`) to get the quantity (say, minimum diameter) in the entire grid. In #1475, the step of calculating cell-wise diameter was skipped; hence the code in some cases gave wrong results for non-simplicial grids.
I am starting to think that the new implementation may be sufficiently general to replace the old implementation, which is activated when setting `cell_wise=True`. However, I am not fully confident that this is really the case, so I would prefer not to do that generalization now, but return to the matter if the cell diameter calculation is taken into much more …
> BUG: Logical error in grid diameter computation

- src/porepy/fracs/fracture_network_2d.py
- src/porepy/fracs/fracture_network_3d.py
- src/porepy/fracs/line_fracture.py
- src/porepy/fracs/plane_fracture.py
Addressing the bulletpoints mentioned in issue 1477:
- Let a FractureNetwork2d export its own domain. Rectangular domains only.
- Let a LineFracture export itself, let the fracture class iterate over its fractures for export.
- Let a FractureNetwork3d export its own domain, boxes only.
- Let a PlaneFracture export itself, fracture network class iterate over fractures for export.
The methods create a gmsh version of the fracture/domain, and return its entity tag.
Note: The documentation is in a sketch stadium. 
> 1477 methods for exporting fracs domains gmsh
